// Auto-generated from app.html SPOTS array. Edit app.html, not this file.
// Used by check.html on file:// (no fetch needed).
window.KODOCO_SPOTS = (function(){
  const SPOTS = [
  // ── 公園 ──────────────────────────────────────────
  {
    id:'yabashi', emoji:'🌳', name:'矢橋帰帆島公園', cat:'公園', catClass:'park',
    loc:'草津市', addr:'滋賀県草津市矢橋町地先', hours:'常時開放', closed:'なし', price:'入園無料',
    desc:'琵琶湖に浮かぶ人工島の広大な公園。ピラミッド型ネット遊具やブランコ、芝生広場があり、0歳の散歩から小学生まで楽しめます。',
    sense:['🌿 自然感あり','🏃 走り回れる','👶 抱っこでOK'],
    keywords:['ピラミッド型ネット遊具','大型ブランコ','ローラーすべり台','芝生広場','サイクリングコース'],
    facilities:['駐車場あり','無料','ベビーカーOK'],
    play:['ピラミッド型ネット遊具','大型ブランコ','ローラーすべり台','芝生広場','サイクリングコース'],
    highlight:'ベビーカーでも回りやすい。琵琶湖の景色が最高。早朝は空いていて気持ちいい。',
    rating:4.2, galleryBg:'linear-gradient(135deg,#c8ede0,#a8d8c4)',
    ageGroups:[0,1,2,3,4,5,6,7], lat:35.0112, lng:135.9483,
    phone:'077-567-1969', officialUrl:'https://hikari-g.com/kihan/',
    parkingSpots:{count:380, free:true, note:'土日は昼前に埋まることあり'},
    durationMin:120, station:'JR草津駅 バス20分',
    weatherProof:'open', reservation:'none',
    accessibility:{wheelchair:true, stroller:'easy'},
    toilets:{diaperChange:true, multipurpose:true, note:'園内3箇所'}
  },
  {
    id:'biwako', emoji:'🌳', name:'びわこ地球市民の森', cat:'公園', catClass:'park',
    loc:'守山市', addr:'滋賀県守山市今浜町2146', hours:'9:00〜17:00', closed:'月曜', price:'無料',
    desc:'守山市の広大な県営公園。大型コンビネーション遊具や冒険の森があり、自然の中でのびのび遊べます。',
    sense:['🌿 自然感あり','🔇 静かめ','🏃 走り回れる'],
    keywords:['大型コンビネーション遊具','冒険の森（木製アスレチック）','ターザンロープ','砂場'],
    facilities:['駐車場あり','無料','ベビーカーOK'],
    play:['大型コンビネーション遊具','冒険の森（木製アスレチック）','ターザンロープ','砂場','バーベキューエリア'],
    highlight:'平日は空いていてゆったり。木製アスレチックは子どもが大興奮。自然の中を散歩するだけでも気持ちいい。',
    rating:4.1, galleryBg:'linear-gradient(135deg,#d0ebd8,#b4d8bc)',
    ageGroups:[1,2,3,4,5,6,7], lat:35.0701, lng:135.9891,
    phone:'077-585-6333', officialUrl:'https://www.moridukuri.info/',
    parkingSpots:{count:400, free:true},
    durationMin:180, station:'JR守山駅 バス15分',
    weatherProof:'open', reservation:'none',
    accessibility:{wheelchair:true, stroller:'easy'}
  },
  {
    id:'kusatsugawa', emoji:'🌿', name:'草津川跡地公園 de愛ひろば', cat:'公園', catClass:'park',
    loc:'草津市', addr:'滋賀県草津市草津3丁目', hours:'9:00〜21:00', closed:'第2火曜', price:'入場無料',
    desc:'旧草津川の跡地を活用した新しい公園。芝生広場やカフェがあり、地域イベントも頻繁に開催。子連れでのんびり過ごせます。',
    sense:['🌿 自然感あり','🔇 静かめ','👶 抱っこでOK'],
    keywords:['芝生広場','カフェ','地域イベント','水遊び場（夏季）'],
    facilities:['無料','ベビーカーOK','飲食可'],
    play:['芝生広場','カフェエリア','水遊び場（夏季限定）','地域マルシェ（定期開催）'],
    highlight:'広い芝生でピクニック気分。カフェのクレープが美味しい。子どもが走り回れる。',
    rating:4.3, galleryBg:'linear-gradient(135deg,#e8f0c8,#d0e4a8)',
    ageGroups:[0,1,2,3,4], lat:35.0156, lng:135.9268
  },
  {
    id:'otsu_park', emoji:'🌳', name:'皇子が丘公園', cat:'公園', catClass:'park',
    loc:'大津市', addr:'滋賀県大津市御陵町1-1', hours:'常時開放', closed:'なし', price:'無料',
    desc:'大津市中心部の丘陵公園。大型すべり台とじゃぶじゃぶ池（夏季）があり、近隣の子育て家族に愛されています。',
    sense:['🌿 自然感あり','🔇 静かめ','🏃 走り回れる'],
    keywords:['大型すべり台','芝生広場','じゃぶじゃぶ池（夏季）','アスレチック'],
    facilities:['無料','ベビーカーOK','駐車場あり'],
    play:['大型すべり台','芝生広場','じゃぶじゃぶ池（夏季）','アスレチック'],
    highlight:'夏のじゃぶじゃぶ池が大人気。駐車場近くて便利。週末は家族連れで賑わう。',
    rating:4.2, galleryBg:'linear-gradient(135deg,#d0f0d8,#b0e0b8)',
    ageGroups:[0,1,2,3,4,5,6], lat:35.0089, lng:135.8598
  },
  {
    id:'moriyama_park', emoji:'🌊', name:'守山市民運動公園', cat:'公園', catClass:'park',
    loc:'守山市', addr:'滋賀県守山市古高町540', hours:'9:00〜17:00', closed:'月曜', price:'無料',
    desc:'守山市の総合運動公園。広い芝生と大型複合遊具が揃い、子どもが1日中遊べます。夏は水遊びエリアも開設。',
    sense:['🌿 自然感あり','🏃 走り回れる','🔊 にぎやか'],
    keywords:['大型複合遊具','芝生広場','水遊びエリア（夏季）','ジョギングコース'],
    facilities:['駐車場あり','無料','ベビーカーOK','飲食可'],
    play:['大型複合遊具','芝生広場','水遊びエリア（夏季）','ターザンロープ','砂場'],
    highlight:'夏の水遊びが人気。複合遊具は年齢別エリアで安心。',
    rating:4.0, galleryBg:'linear-gradient(135deg,#c8e8f8,#a8d0f0)',
    ageGroups:[0,1,2,3,4,5,6,7], lat:35.0523, lng:135.9934
  },

  // ── 室内遊び場 ────────────────────────────────────
  {
    id:'asoble', emoji:'🏠', name:'ASOBLEオーミー大津テラス店', cat:'室内遊び場', catClass:'indoor',
    loc:'大津市', addr:'滋賀県大津市打出浜2-1', hours:'10:00〜18:00', closed:'不定休', price:'子ども500円/30分〜',
    desc:'大津市の室内遊び場。ボールプールやトランポリン、おままごとコーナーなど多彩な遊びが楽しめます。雨の日でも安心。',
    sense:['🏗 施設感つよい','🔊 にぎやか','👶 抱っこでOK'],
    keywords:['ボールプール','トランポリン','おままごとコーナー','室内砂場'],
    facilities:['おむつ替え','授乳室','雨の日OK','駐車場あり'],
    play:['ボールプール','トランポリン','おままごとコーナー','室内砂場','キッズカー'],
    highlight:'0歳から入れる。雨の日の定番。週末は混むので平日狙いがおすすめ。',
    rating:3.9, galleryBg:'linear-gradient(135deg,#fce8d0,#f8d4b0)',
    ageGroups:[0,1,2,3], lat:35.0145, lng:135.8612,
    durationMin:90, station:'JR膳所駅 徒歩8分',
    weatherProof:'indoor', reservation:'recommended',
    toilets:{diaperChange:true, multipurpose:true},
    nursingRoom:{available:true, private:true, hotWater:true},
    accessibility:{wheelchair:true, stroller:'easy'}
  },
  {
    id:'otsu_child', emoji:'🍼', name:'大津市子育て交流施設 ほっとステーション', cat:'室内遊び場', catClass:'indoor',
    loc:'大津市', addr:'滋賀県大津市浜大津4丁目', hours:'10:00〜16:00', closed:'日・月・祝', price:'無料',
    desc:'0〜3歳向けの子育て支援施設。授乳室・おむつ替え完備で、ねんね期のお子さんも安心して過ごせます。親同士の交流の場にも。',
    sense:['🏗 施設感つよい','🔇 静かめ','👶 抱っこでOK'],
    keywords:['0〜3歳専用','授乳室','おむつ替え','親子交流','スタッフ常駐'],
    facilities:['無料','おむつ替え','授乳室','ベビーカーOK','雨の日OK'],
    play:['マット遊びエリア','ハイハイコーナー','絵本・おもちゃ','親子体操（定期開催）'],
    highlight:'0歳でも安心して遊べる。スタッフが常駐していて相談もできる。同じ月齢の親と仲良くなれる。',
    rating:4.4, galleryBg:'linear-gradient(135deg,#fce8f8,#f8d0f0)',
    ageGroups:[0,1,2,3], lat:35.0067, lng:135.8689
  },
  {
    id:'challenge_museum', emoji:'🔬', name:'チャレンジミュージアム', cat:'室内遊び場', catClass:'indoor',
    loc:'甲賀市', addr:'滋賀県甲賀市水口町水口5600', hours:'9:30〜17:00', closed:'月曜', price:'大人300円・子ども100円',
    desc:'「やってみよう！わくわく未来チャレンジ」をコンセプトにした体験型ミュージアム。見て・触れて・体験しながら学べます。',
    sense:['🏗 施設感つよい','🔊 にぎやか','🏃 走り回れる'],
    keywords:['科学体験','工作コーナー','デジタル体験','自然学習'],
    facilities:['駐車場あり','雨の日OK','おむつ替え'],
    play:['科学実験コーナー','工作体験','デジタル体験ゾーン','自然学習展示'],
    highlight:'雨の日でも1日楽しめる。スタッフが実験を教えてくれる。小学生になっても来られる。',
    rating:4.2, galleryBg:'linear-gradient(135deg,#e0f0ff,#c0d8f8)',
    ageGroups:[3,4,5,6,7,8,9,10], lat:34.9723, lng:136.1634
  },

  // ── カフェ・レストラン ────────────────────────────
  {
    id:'chalet', emoji:'☕', name:'シャーレ水ヶ浜', cat:'カフェ・レストラン', catClass:'cafe',
    loc:'近江八幡市', addr:'滋賀県近江八幡市長命寺町水ヶ浜182-8', hours:'11:00〜17:00', closed:'不定休', price:'ランチ1,000円〜',
    desc:'琵琶湖湖畔ぎりぎりのログハウス風カフェ。テラス席から琵琶湖を望む絶景が人気。ホットサンドとカレーが定番メニュー。',
    sense:['🌿 自然感あり','🔇 静かめ','👶 抱っこでOK'],
    keywords:['琵琶湖テラス席','ホットサンド','カレー','湖畔カフェ'],
    facilities:['駐車場あり','テラス席','飲食可'],
    play:['テラスで琵琶湖を眺める','水辺の散歩','アヒルに会える'],
    highlight:'テラスから琵琶湖が目の前。週末は混むので早めに到着推奨。水辺に降りれて子どもが大喜び。',
    rating:4.4, galleryBg:'linear-gradient(135deg,#d0e8f8,#b0d0f0)',
    ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.1523, lng:136.0812
  },
  {
    id:'loco_cafe', emoji:'☕', name:'子育て応援カフェ LOCO', cat:'カフェ・レストラン', catClass:'cafe',
    loc:'米原市', addr:'滋賀県米原市', hours:'10:00〜16:00', closed:'日・月', price:'ドリンク500円〜',
    desc:'ママたちのためのコミュニティーカフェ。赤ちゃんと一緒のお出かけに必要なものがほとんど揃っています。',
    sense:['🏗 施設感つよい','🔇 静かめ','👶 抱っこでOK'],
    keywords:['授乳室完備','キッズスペース','ベビーリクライニングチェア','ママ会'],
    facilities:['おむつ替え','授乳室','ベビーカーOK','雨の日OK','キッズスペース'],
    play:['キッズスペース','絵本コーナー','ママ向けワークショップ'],
    highlight:'新生児から使えるベビーリクライニングチェアが◎。ママ同士の交流の場として人気。',
    rating:4.5, galleryBg:'linear-gradient(135deg,#fce8e8,#f8d0d0)',
    ageGroups:[0,1,2,3], lat:35.3156, lng:136.2812
  },
  {
    id:'higoro', emoji:'🍽', name:'higoro TERRACE（ヒゴロテラス）', cat:'カフェ・レストラン', catClass:'cafe',
    loc:'近江八幡市', addr:'滋賀県近江八幡市佐波江町242-1', hours:'11:00〜16:00（11〜4月）/11:00〜17:00（5〜10月）', closed:'火曜', price:'ランチ1,200円〜',
    desc:'琵琶湖湖畔の食堂カフェ。滋賀県産食材を使った「地産地消」の定食が人気。子どもイスやぬりえ・絵本も完備。',
    sense:['🌿 自然感あり','🔇 静かめ','👶 抱っこでOK'],
    keywords:['地産地消ランチ','琵琶湖ビュー','子どもイス','おむつ替えシート'],
    facilities:['駐車場あり','おむつ替え','飲食可','子どもイス'],
    play:['ぬりえ・絵本コーナー','大きな窓から田園風景'],
    highlight:'週替わり定食が美味しい。大きな窓から田園風景が見える。子どもに優しい接客が嬉しい。',
    rating:4.3, galleryBg:'linear-gradient(135deg,#f0e8d0,#e8d4b0)',
    ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.1378, lng:136.0545
  },
  {
    id:'ichigo_milk', emoji:'🍓', name:'カフェ＆BBQ いちごとミルク', cat:'カフェ・レストラン', catClass:'cafe',
    loc:'長浜市', addr:'滋賀県長浜市', hours:'11:00〜17:00（土日祝10:30〜18:00）', closed:'月曜', price:'スイーツ600円〜',
    desc:'農園育ちのイチゴを使ったスイーツとBBQが楽しめる体験型カフェ。屋内BBQブースで天候を気にせず楽しめます。',
    sense:['🌿 自然感あり','🔊 にぎやか','🏃 走り回れる'],
    keywords:['いちごスイーツ','屋内BBQ','体験型カフェ','テイクアウト'],
    facilities:['駐車場あり','飲食可','雨の日OK'],
    play:['いちごスイーツ体験','屋内BBQ','フルーツ狩り（季節限定）'],
    highlight:'いちごスイーツが絶品。屋内BBQなので雨でも安心。子どもが自分でBBQする体験が好評。',
    rating:4.2, galleryBg:'linear-gradient(135deg,#fce8e8,#f8c8c8)',
    ageGroups:[2,3,4,5,6,7,8,9,10], lat:35.3823, lng:136.2456
  },
  {
    id:'makino', emoji:'🍇', name:'マキノピックランド', cat:'カフェ・レストラン', catClass:'cafe',
    loc:'高島市', addr:'滋賀県高島市マキノ町海津2352', hours:'9:00〜17:00', closed:'不定休', price:'果物狩り600円〜',
    desc:'季節ごとの果物狩りが楽しめる体験型農園。さくらんぼ・ブルーベリー・ぶどう・りんごと年間通して楽しめます。',
    sense:['🌿 自然感あり','🔊 にぎやか','🏃 走り回れる'],
    keywords:['果物狩り','ブルーベリー','ぶどう','りんご','さくらんぼ'],
    facilities:['駐車場あり','飲食可'],
    play:['果物狩り（季節により異なる）','直売所でお買い物'],
    highlight:'子どもが自分で収穫する体験は特別。食べ放題プランも人気。季節ごとに来られる。',
    rating:4.3, galleryBg:'linear-gradient(135deg,#e8f0d0,#d0e4a8)',
    ageGroups:[2,3,4,5,6,7,8,9,10], lat:35.4823, lng:136.0234,
    phone:'0740-27-1811', officialUrl:'https://pic-land.com/'
  },

  // ── ミュージアム・体験 ────────────────────────────
  {
    id:'mentai', emoji:'🏛', name:'めんたいパークびわ湖', cat:'ミュージアム・体験', catClass:'museum',
    loc:'野洲市', addr:'滋賀県野洲市吉川4187', hours:'9:30〜17:30', closed:'不定休', price:'入場無料',
    desc:'明太子のテーマパーク。2階には0-2歳専用の遊び場があり、授乳室も完備。フードコーナーで明太子グルメも楽しめます。',
    sense:['🏗 施設感つよい','🔊 にぎやか','👶 抱っこでOK'],
    keywords:['0-2歳専用遊び場','明太子工場見学','めんたいフードコーナー','ミニゲームコーナー'],
    facilities:['駐車場あり','おむつ替え','授乳室','雨の日OK','飲食可'],
    play:['0-2歳専用遊び場（2階）','明太子工場見学（ガラス越し）','めんたいフードコーナー','ミニゲームコーナー','お土産ショップ'],
    highlight:'授乳室が2階にあり静か。工場見学は子どもウケ抜群。明太子おにぎり絶品。',
    rating:4.0, galleryBg:'linear-gradient(135deg,#cfe0f8,#b0c8f0)',
    ageGroups:[0,1,2,3], lat:35.0756, lng:136.0012,
    phone:'077-589-8105', officialUrl:'https://mentai-park.com/biwako/'
  },
  {
    id:'nagahama_rail', emoji:'🚂', name:'長浜鉄道スクエア', cat:'ミュージアム・体験', catClass:'museum',
    loc:'長浜市', addr:'滋賀県長浜市北船町1-41', hours:'9:30〜17:00', closed:'月曜', price:'大人300円・小学生100円',
    desc:'日本最古の駅舎を活用した鉄道博物館。本物の機関車や客車が間近で見られ、乗り物好きな子どもに大人気。',
    sense:['🏗 施設感つよい','🔇 静かめ','🔊 にぎやか'],
    keywords:['本物の機関車展示','旧長浜駅舎','鉄道ジオラマ','SL見学'],
    facilities:['駐車場あり','雨の日OK'],
    play:['機関車・客車展示','鉄道ジオラマ','歴史展示','旧駅舎見学'],
    highlight:'本物の機関車に乗れる体験が人気。雨の日でも楽しめる。長浜の街散策とセットで。',
    rating:4.1, galleryBg:'linear-gradient(135deg,#e8d8f0,#d0b8e8)',
    ageGroups:[2,3,4,5,6,7,8,9,10], lat:35.3782, lng:136.2698,
    phone:'0749-63-4091', officialUrl:'https://kitabiwako.jp/tetsudou/'
  },
  {
    id:'shigaraki', emoji:'🦝', name:'信楽陶苑 たぬき村', cat:'ミュージアム・体験', catClass:'museum',
    loc:'甲賀市', addr:'滋賀県甲賀市信楽町長野1131', hours:'9:00〜17:00', closed:'水曜', price:'絵付け体験1,500円〜',
    desc:'信楽焼で有名なたぬき村。どこを見てもたぬきだらけ！信楽焼の絵付け体験ができ、オリジナル作品を持ち帰れます。',
    sense:['🌿 自然感あり','🔊 にぎやか','🏗 施設感つよい'],
    keywords:['信楽焼絵付け体験','たぬきオブジェ','お土産ショップ','陶芸体験'],
    facilities:['駐車場あり','飲食可','雨の日OK'],
    play:['絵付け体験','たぬきオブジェ巡り','陶芸体験','お土産選び'],
    highlight:'世界最大のたぬきがいる！絵付け体験は小さい子でも楽しめる。家族の記念品にも最適。',
    rating:4.0, galleryBg:'linear-gradient(135deg,#f0e0d0,#e0c8b0)',
    ageGroups:[2,3,4,5,6,7,8,9,10], lat:34.8923, lng:136.0234,
    officialUrl:'https://tanukimura.com/'
  },
  {
    id:'biwako_cruise', emoji:'🚢', name:'琵琶湖汽船ミシガン', cat:'ミュージアム・体験', catClass:'museum',
    loc:'大津市', addr:'滋賀県大津市浜大津5丁目1-1', hours:'10:30〜', closed:'運航日要確認', price:'大人2,500円〜・子ども1,250円〜',
    desc:'赤いパドルが目印の大型観光船。琵琶湖を優雅にクルーズし、最上階スカイデッキから360°の絶景を楽しめます。',
    sense:['🌿 自然感あり','🔊 にぎやか','🏗 施設感つよい'],
    keywords:['琵琶湖クルーズ','スカイデッキ','360°絶景','大型観光船'],
    facilities:['おむつ替え','授乳室','飲食可'],
    play:['デッキからの絶景鑑賞','船内レストラン','船内イベント'],
    highlight:'非日常感が最高。子どもは船の操舵室見学が人気。天気のいい日は最高の思い出に。',
    rating:4.3, galleryBg:'linear-gradient(135deg,#c8e0f8,#a8c8f0)',
    ageGroups:[1,2,3,4,5,6,7,8,9,10], lat:35.0089, lng:135.8723,
    officialUrl:'https://www.biwakokisen.co.jp/cruise/michigan/'
  },
  // ── 公園（追加）────────────────────────────────
  {
    id:'kibogaoka', emoji:'🌳', name:'希望が丘文化公園', cat:'公園', catClass:'park',
    loc:'野洲市・竜王町', addr:'滋賀県野洲市二ツ池1234', hours:'9:00〜17:00', closed:'月曜', price:'入園無料・駐車場500円',
    desc:'滋賀県民の定番おでかけスポット。芝生の原っぱがどこまでも続き、バドミントンやフリスビーなど自由に楽しめます。本格的なフィールドアスレチックも。',
    sense:['🌿 自然感あり','🏃 走り回れる','🔊 にぎやか'],
    keywords:['芝生広場','フィールドアスレチック','バーベキュー','サイクリングコース'],
    facilities:['駐車場あり','飲食可','ベビーカーOK'],
    play:['フィールドアスレチック','芝生広場','バーベキューエリア','サイクリングコース'],
    highlight:'とにかく広い！1日いられる。芝生でお弁当が最高。アスレチックは本格的で子どもが大興奮。',
    rating:4.3, galleryBg:'linear-gradient(135deg,#c8ede0,#a0d8c0)',
    ageGroups:[2,3,4,5,6,7,8,9,10], lat:35.0234, lng:136.0123,
    phone:'077-586-2111', officialUrl:'https://www.kiboupark-shiga.or.jp/'
  },
  {
    id:'blueme', emoji:'🌸', name:'ブルーメの丘', cat:'公園', catClass:'park',
    loc:'日野町', addr:'滋賀県蒲生郡日野町西大路843', hours:'10:00〜17:00', closed:'水曜', price:'大人1,000円・子ども600円',
    desc:'ドイツの田舎町を模した体験型農業公園。四季の花畑と動物ふれあい、アスレチックタワーやジップラインが充実。お菓子作り体験も人気。',
    sense:['🌿 自然感あり','🔊 にぎやか','🏃 走り回れる'],
    keywords:['花畑','動物ふれあい','アスレチックタワー','ジップライン','お菓子作り体験'],
    facilities:['駐車場あり','飲食可','おむつ替え'],
    play:['動物ふれあいコーナー','アスレチックタワー（高さ17m）','ジップライン','季節の花畑','お菓子作り体験'],
    highlight:'季節ごとに花の景色が変わる。動物ふれあいは小さい子でも大丈夫。BBQも楽しめる。',
    rating:4.2, galleryBg:'linear-gradient(135deg,#f8e8f0,#f0c8e0)',
    ageGroups:[1,2,3,4,5,6,7,8,9,10], lat:35.0089, lng:136.1234,
    phone:'0748-52-2611', officialUrl:'https://www.blumenooka.jp/'
  },
  {
    id:'biwako_kodomo', emoji:'🎪', name:'びわ湖こどもの国', cat:'公園', catClass:'park',
    loc:'高島市', addr:'滋賀県高島市今津町弘川1771-2', hours:'9:30〜17:00', closed:'月曜', price:'入場無料・駐車場500円',
    desc:'入場料無料で1日楽しめる子どもの楽園。ふわふわ遊具やボルダリング、おもしろ自転車、水遊び場など多彩。雨の日でも屋内で遊べる施設あり。',
    sense:['🌿 自然感あり','🏃 走り回れる','🔊 にぎやか'],
    keywords:['ふわふわ遊具','ボルダリング','おもしろ自転車','水遊び場（夏季）','トランポリン'],
    facilities:['駐車場あり','無料','おむつ替え','ベビーカーOK'],
    play:['ふわふわ遊具','ボルダリング','おもしろ自転車','水遊び場（夏季）','工作教室'],
    highlight:'入場無料なのに内容が充実。おもしろ自転車は子どもが大喜び。平日は空いていて快適。',
    rating:4.4, galleryBg:'linear-gradient(135deg,#d0e8f8,#b0d0f0)',
    ageGroups:[1,2,3,4,5,6,7,8,9,10], lat:35.4123, lng:136.0456,
    officialUrl:'http://www.biwa.ne.jp/~kodomo92/'
  },
  {
    id:'hikone_park', emoji:'🏯', name:'彦根城・玄宮園', cat:'公園', catClass:'park',
    loc:'彦根市', addr:'滋賀県彦根市金亀町1-1', hours:'8:30〜17:00', closed:'なし', price:'大人800円・子ども無料',
    desc:'国宝の彦根城を中心とした公園。ひこにゃんが出迎えてくれる。玄宮園は春の桜・秋の紅葉が美しく、お城を背景にした景色が絶景。',
    sense:['🌿 自然感あり','🔇 静かめ','🏗 施設感つよい'],
    keywords:['国宝彦根城','ひこにゃん','玄宮園','桜の名所'],
    facilities:['駐車場あり','飲食可'],
    play:['ひこにゃんに会う','天守からの眺め','玄宮園の庭園散策','堀をぐるっと一周'],
    highlight:'ひこにゃんの登場時間をチェックして行くと子どもが大喜び。お城周りの堀端の散歩が気持ちいい。',
    rating:4.5, galleryBg:'linear-gradient(135deg,#f0e8d0,#e0d0a8)',
    ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.2762, lng:136.2515,
    officialUrl:'https://hikonecastle.com/'
  },

  // ── 室内遊び場（追加）───────────────────────────
  {
    id:'kidsusland', emoji:'🏠', name:'キッズユーエスランド 近江八幡店', cat:'室内遊び場', catClass:'indoor',
    loc:'近江八幡市', addr:'滋賀県近江八幡市鷹飼町南3-7 イオン近江八幡店内', hours:'10:00〜19:00', closed:'不定休', price:'平日600円〜・休日800円〜',
    desc:'イオン内の室内遊び場。スーパージャングルジムやボールプール、トランポリン、ふわふわ遊具が充実。ショッピングついでに立ち寄れる便利なロケーション。',
    sense:['🏗 施設感つよい','🔊 にぎやか','👶 抱っこでOK'],
    keywords:['スーパージャングルジム','ボールプール','トランポリン','ふわふわ遊具','ゲームフリープレイ'],
    facilities:['駐車場あり','雨の日OK','おむつ替え','授乳室'],
    play:['スーパージャングルジム','ボールプール','トランポリン','ふわふわ遊具','設置ゲームフリープレイ'],
    highlight:'イオンの中なので買い物と合わせて行きやすい。ゲームフリープレイが嬉しい。雨の日の定番。',
    rating:4.0, galleryBg:'linear-gradient(135deg,#fce8d0,#f8c8a0)',
    ageGroups:[0,1,2,3,4,5,6,7], lat:35.1234, lng:136.0912
  },
  {
    id:'kodomotchi', emoji:'🏠', name:'こどもっちパーク栗東', cat:'室内遊び場', catClass:'indoor',
    loc:'栗東市', addr:'滋賀県栗東市綣2-4-5 パワーシティ栗東内', hours:'10:00〜19:00', closed:'不定休', price:'平日500円〜・休日700円〜',
    desc:'栗東市の室内遊び場。遊具がいっぱいで0歳から遊べる。ショッピングモール内なので雨の日でも安心。授乳室・おむつ替えも完備。',
    sense:['🏗 施設感つよい','🔊 にぎやか','👶 抱っこでOK'],
    keywords:['大型遊具','ボールプール','ふわふわ遊具','キッズカー'],
    facilities:['駐車場あり','雨の日OK','おむつ替え','授乳室'],
    play:['大型複合遊具','ボールプール','ふわふわ遊具','キッズカー'],
    highlight:'南部エリアで便利な立地。ショッピングのついでに立ち寄れる。0歳から入れる。',
    rating:3.9, galleryBg:'linear-gradient(135deg,#e8f0ff,#c8d8f8)',
    ageGroups:[0,1,2,3,4,5], lat:35.0012, lng:135.9845
  },
  {
    id:'yanmar', emoji:'🔬', name:'ヤンマーミュージアム', cat:'室内遊び場', catClass:'indoor',
    loc:'長浜市', addr:'滋賀県長浜市三和町6-50', hours:'10:00〜17:00', closed:'月曜', price:'大人800円・小中学生400円・幼児無料',
    desc:'見て触って体験できる体験型ミュージアム。ものづくり体験やビオトープ、足湯なども。全身を使ったアトラクションが多く、雨の日でも思いっきり楽しめる。',
    sense:['🏗 施設感つよい','🔊 にぎやか','🏃 走り回れる'],
    keywords:['体験型展示','ものづくり体験','ビオトープ','足湯','シミュレーター'],
    facilities:['駐車場あり','雨の日OK','飲食可'],
    play:['農業機械シミュレーター','ものづくり体験','ビオトープ観察','足湯','体を使ったアトラクション'],
    highlight:'幼児は入場無料。農業機械のシミュレーターが子どもに大人気。足湯でゆったりできる。',
    rating:4.3, galleryBg:'linear-gradient(135deg,#e0f0e8,#c0e0d0)',
    ageGroups:[2,3,4,5,6,7,8,9,10], lat:35.3891, lng:136.2734,
    officialUrl:'https://www.yanmar.com/jp/museum/'
  },
  {
    id:'biwako_museum', emoji:'🐟', name:'滋賀県立琵琶湖博物館', cat:'室内遊び場', catClass:'indoor',
    loc:'草津市', addr:'滋賀県草津市下物町1091', hours:'9:30〜17:00', closed:'月曜', price:'大人800円・高校生450円・小中学生無料',
    desc:'滋賀が誇る大規模水族＆博物館。琵琶湖の生き物が間近で見られる水族展示が充実。子どもが喜ぶ体験コーナーも多数。',
    sense:['🏗 施設感つよい','🔇 静かめ','🌿 自然感あり'],
    keywords:['琵琶湖の魚','水族展示','体験学習','ディスカバリールーム'],
    facilities:['駐車場あり','雨の日OK','おむつ替え','授乳室','飲食可'],
    play:['水族展示（琵琶湖の生き物）','ディスカバリールーム','体験展示','図書コーナー'],
    highlight:'小中学生は無料！大型の水槽で琵琶湖の魚が間近に見られる。1日いられる充実度。',
    rating:4.4, galleryBg:'linear-gradient(135deg,#c8e8f8,#a0c8f0)',
    ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.0156, lng:135.9623,
    officialUrl:'https://www.biwahaku.jp/'
  },

  // ── カフェ・レストラン（追加）──────────────────────
  {
    id:'lacolina', emoji:'🍰', name:'ラコリーナ近江八幡', cat:'カフェ・レストラン', catClass:'cafe',
    loc:'近江八幡市', addr:'滋賀県近江八幡市北之庄町615-1', hours:'9:00〜18:00', closed:'不定休', price:'バームクーヘン500円〜',
    desc:'たねや・クラブハリエが運営する自然共生型複合施設。草屋根のメインショップが圧巻の景観。焼きたてバームクーヘンとカフェが人気で、広大な田んぼアートも楽しめる。',
    sense:['🌿 自然感あり','🔇 静かめ','👶 抱っこでOK'],
    keywords:['バームクーヘン','草屋根','田んぼアート','焼きたてスイーツ','カフェ'],
    facilities:['駐車場あり','飲食可','ベビーカーOK','おむつ替え'],
    play:['バームクーヘン体験','田んぼアート鑑賞','広大な庭園散策','スイーツ購入'],
    highlight:'インスタ映え間違いなし。バームクーヘンの焼きたては絶品。広い敷地で子どもも走り回れる。',
    rating:4.6, galleryBg:'linear-gradient(135deg,#e8f0d8,#d0e8b8)',
    ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.1289, lng:136.0823,
    officialUrl:'https://taneya.jp/la_collina/'
  },
  {
    id:'teraitei', emoji:'🍽', name:'teraitei（テライテイ）', cat:'カフェ・レストラン', catClass:'cafe',
    loc:'彦根市', addr:'滋賀県彦根市四番町スクエア内', hours:'11:00〜15:00・17:00〜21:00', closed:'火曜', price:'ランチ1,000円〜',
    desc:'彦根城のお膝元、大正時代の街並み「四番町スクエア」内のカフェ。子どもたちと楽しく食事しながらリラックスできる空間。子どもイス完備。',
    sense:['🏗 施設感つよい','🔇 静かめ','👶 抱っこでOK'],
    keywords:['彦根城近く','大正ロマン','子どもイス','ランチ'],
    facilities:['駐車場あり','飲食可','子どもイス'],
    play:['街並み散策','彦根城観光とセット','ゆったりランチ'],
    highlight:'彦根城観光のランチにぴったり。大正時代の街並みが雰囲気抜群。子連れにやさしい接客。',
    rating:4.2, galleryBg:'linear-gradient(135deg,#f8f0e0,#f0e0c0)',
    ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.2734, lng:136.2512
  },
  {
    id:'minakuchi_cafe', emoji:'☕', name:'みなくち子どもの森 自然館カフェ', cat:'カフェ・レストラン', catClass:'cafe',
    loc:'甲賀市', addr:'滋賀県甲賀市水口町北内貴10', hours:'9:00〜17:00', closed:'月曜', price:'入場無料・カフェ300円〜',
    desc:'甲賀市の穴場スポット。体験型の小規模博物館に併設のカフェ。化石のトンネルやミニプラネタリウムあり。自然の中でゆったりランチができる。',
    sense:['🌿 自然感あり','🔇 静かめ','👶 抱っこでOK'],
    keywords:['自然館','ミニプラネタリウム','化石トンネル','ピクニックエリア'],
    facilities:['駐車場あり','無料','飲食可','ベビーカーOK'],
    play:['ミニプラネタリウム','化石トンネル体験','自然観察','ピクニックエリアでランチ'],
    highlight:'穴場スポットで空いている。入場無料なのに内容充実。自然の中でのランチが気持ちいい。',
    rating:4.1, galleryBg:'linear-gradient(135deg,#d8f0d0,#b8e0b0)',
    ageGroups:[1,2,3,4,5,6,7,8,9,10], lat:34.9678, lng:136.1712
  },

  // ── ミュージアム・体験（追加）──────────────────────
  {
    id:'hikone_sky', emoji:'🧗', name:'ひこねスカイアドベンチャー', cat:'ミュージアム・体験', catClass:'museum',
    loc:'彦根市', addr:'滋賀県彦根市古沢町（JR彦根駅から徒歩15分）', hours:'10:00〜17:00', closed:'火曜', price:'2G：大人2,200円・4歳〜小学生1,100円',
    desc:'JR彦根駅から徒歩15分。スリルや達成感を楽しめるアドベンチャー施設。4歳から体験できる2Gコースで、安全に空中冒険ができる。',
    sense:['🌿 自然感あり','🏃 走り回れる','🔊 にぎやか'],
    keywords:['アドベンチャー','空中アスレチック','ジップライン','クライミング'],
    facilities:['駐車場あり'],
    play:['空中アスレチック（2Gコース）','ジップライン','クライミング','3Gコース（上級）'],
    highlight:'4歳から挑戦できる。達成感が最高。スタッフが丁寧にサポートしてくれるので初めてでも安心。',
    rating:4.4, galleryBg:'linear-gradient(135deg,#e8f8e8,#c0e8c0)',
    ageGroups:[4,5,6,7,8,9,10], lat:35.2712, lng:136.2534
  },
  {
    id:'ceramic_forest', emoji:'🏺', name:'滋賀県立陶芸の森', cat:'ミュージアム・体験', catClass:'museum',
    loc:'甲賀市', addr:'滋賀県甲賀市信楽町勅旨2188-7', hours:'9:30〜17:00', closed:'月曜', price:'展示館：大人500円・高校生以下無料',
    desc:'信楽焼をテーマにした文化施設。屋外には多くの陶芸作品が並ぶ広場があり、定期的に陶芸体験教室も開催。自然の中でアートに触れられる。',
    sense:['🌿 自然感あり','🔇 静かめ','🏗 施設感つよい'],
    keywords:['陶芸体験','信楽焼','野外彫刻','ワークショップ'],
    facilities:['駐車場あり','飲食可'],
    play:['陶芸体験（要予約）','野外彫刻鑑賞','信楽焼展示','ワークショップ'],
    highlight:'高校生以下無料。陶芸体験は子どもに大人気。のんびりした雰囲気がいい。',
    rating:4.1, galleryBg:'linear-gradient(135deg,#f0e8d8,#e0d0b8)',
    ageGroups:[3,4,5,6,7,8,9,10], lat:34.8934, lng:136.0312
  },
  {
    id:'otsu_science', emoji:'🔭', name:'大津市科学館', cat:'ミュージアム・体験', catClass:'museum',
    loc:'大津市', addr:'滋賀県大津市本丸町6-50', hours:'9:30〜17:00', closed:'月曜', price:'大人510円・高校生310円・小中学生200円・未就学児無料',
    desc:'お手頃価格で楽しめる科学館。プラネタリウムや体験展示が充実。未就学児は無料なのでお財布にやさしい。雨の日の定番スポット。',
    sense:['🏗 施設感つよい','🔇 静かめ','🔊 にぎやか'],
    keywords:['プラネタリウム','体験展示','科学実験','工作'],
    facilities:['駐車場あり','雨の日OK'],
    play:['プラネタリウム','体験展示','科学実験コーナー','工作ワークショップ'],
    highlight:'未就学児無料が嬉しい。プラネタリウムは迫力満点。雨の日でも親子でたっぷり楽しめる。',
    rating:4.2, galleryBg:'linear-gradient(135deg,#e8e0f8,#d0c8f0)',
    ageGroups:[2,3,4,5,6,7,8,9,10], lat:35.0023, lng:135.8712,
    phone:'077-522-1907', officialUrl:'http://www.otsu.ed.jp/kagaku/'
  },

  // ── 公園・自然（追加）───────────────────────────
  {
    id:'agripark', emoji:'🐄', name:'アグリパーク竜王', cat:'公園', catClass:'park',
    loc:'竜王町', addr:'滋賀県蒲生郡竜王町山之上6526', hours:'9:00〜17:00', closed:'月曜', price:'入園無料・体験別料金',
    desc:'農業体験と動物ふれあいが楽しめる公園。田植え・稲刈り・野菜収穫など季節の農業体験ができ、牛・羊・ウサギとのふれあいコーナーも人気。',
    sense:['🌿 自然感あり','🏃 走り回れる','🔊 にぎやか'],
    keywords:['農業体験','動物ふれあい','いちご狩り（季節限定）','田植え・稲刈り'],
    facilities:['駐車場あり','無料','飲食可','おむつ替え'],
    play:['動物ふれあいコーナー','農業体験（季節により異なる）','広大な芝生広場','いちご狩り（春季）'],
    highlight:'入園無料なのに充実した内容。泥で田植えする体験は子どもが大喜び。動物が近くで見られる。',
    rating:4.2, galleryBg:'linear-gradient(135deg,#e0f0c8,#c8e4a0)',
    ageGroups:[1,2,3,4,5,6,7,8,9,10], lat:35.0456, lng:136.1023,
    officialUrl:'https://www.aguri-p.com/'
  },
  {
    id:'biwako_valley', emoji:'🏔', name:'びわ湖バレイ・びわ湖テラス', cat:'公園', catClass:'park',
    loc:'大津市', addr:'滋賀県大津市木戸1547-1', hours:'9:00〜17:00', closed:'不定休', price:'ロープウェイ大人2,600円〜・3歳以下無料',
    desc:'琵琶湖を一望できる山頂リゾート。ロープウェイで登る絶景のびわ湖テラスが人気。夏は山頂での涼しい過ごし方が魅力。',
    sense:['🌿 自然感あり','🔇 静かめ','🏃 走り回れる'],
    keywords:['びわ湖テラス','絶景ロープウェイ','山頂散策','3歳以下無料'],
    facilities:['駐車場あり','飲食可'],
    play:['ロープウェイ乗車','びわ湖テラスで絶景','山頂散策','冬はスキー・スノーボード'],
    highlight:'3歳以下無料。山頂からの琵琶湖の景色は圧巻。夏は涼しくて最高の避暑地。',
    rating:4.4, galleryBg:'linear-gradient(135deg,#c8d8f8,#a8bce8)',
    ageGroups:[1,2,3,4,5,6,7,8,9,10], lat:35.1234, lng:135.9012,
    officialUrl:'https://www.biwako-valley.com/'
  },
  {
    id:'karasuma_botanical', emoji:'🌸', name:'烏丸半島水生植物公園みずの森', cat:'公園', catClass:'park',
    loc:'草津市', addr:'滋賀県草津市下物町1091-4', hours:'9:00〜17:00', closed:'月曜', price:'大人300円・中学生以下無料',
    desc:'琵琶湖湖畔の植物園。ハスやスイレンなどの水生植物をメインに多くの植物が栽培。「水と人のふれあい」をテーマに親子でゆったり過ごせる。',
    sense:['🌿 自然感あり','🔇 静かめ','👶 抱っこでOK'],
    keywords:['ハス・スイレン','水生植物','温室','琵琶湖湖畔散策'],
    facilities:['駐車場あり','ベビーカーOK','おむつ替え'],
    play:['水生植物観察','温室見学','湖畔散策','季節の花鑑賞'],
    highlight:'中学生以下無料。ハスの花が咲く夏が特におすすめ。ベビーカーで回りやすい。',
    rating:4.1, galleryBg:'linear-gradient(135deg,#d8f0e8,#b8e0d0)',
    ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.0089, lng:135.9534
  },
  {
    id:'nagahama_park', emoji:'🌳', name:'豊公園（長浜城跡）', cat:'公園', catClass:'park',
    loc:'長浜市', addr:'滋賀県長浜市公園町10-10', hours:'常時開放', closed:'なし', price:'無料（長浜城歴史博物館は別途）',
    desc:'長浜城跡を整備した公園。琵琶湖沿いに広がる芝生広場でピクニックが楽しめる。春の桜が有名で、子どもが走り回れる広大なスペースあり。',
    sense:['🌿 自然感あり','🏃 走り回れる','🔇 静かめ'],
    keywords:['長浜城跡','琵琶湖沿い','桜の名所','芝生広場'],
    facilities:['駐車場あり','無料','ベビーカーOK'],
    play:['芝生広場でピクニック','長浜城見学（有料）','琵琶湖沿い散策','春の桜鑑賞'],
    highlight:'春の桜と琵琶湖のコラボが絶景。広い芝生でのびのび遊べる。長浜の街歩きとセット。',
    rating:4.2, galleryBg:'linear-gradient(135deg,#f8e8f0,#f0c8e0)',
    ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.3845, lng:136.2723
  },
  {
    id:'hibari_park', emoji:'🌳', name:'ひばり公園', cat:'公園', catClass:'park',
    loc:'草津市', addr:'滋賀県草津市野路5丁目', hours:'常時開放', closed:'なし', price:'無料',
    desc:'草津市の人気公園。大型複合遊具とじゃぶじゃぶ池（夏季）が充実。地元ファミリーに愛される定番スポット。週末はにぎわう。',
    sense:['🌿 自然感あり','🏃 走り回れる','🔊 にぎやか'],
    keywords:['大型複合遊具','じゃぶじゃぶ池（夏季）','砂場','広場'],
    facilities:['無料','ベビーカーOK','駐車場あり'],
    play:['大型複合遊具','じゃぶじゃぶ池（夏季）','砂場','芝生広場'],
    highlight:'地元民の定番。夏のじゃぶじゃぶ池が大人気。近くのイオンとセットで行きやすい。',
    rating:4.0, galleryBg:'linear-gradient(135deg,#d0ecd8,#b0d8b8)',
    ageGroups:[0,1,2,3,4,5,6,7], lat:35.0034, lng:135.9423
  },

  // ── 室内遊び場（追加）────────────────────────────
  {
    id:'zakids_kusatsu', emoji:'🏠', name:'ザキッズ エイスクエア草津店', cat:'室内遊び場', catClass:'indoor',
    loc:'草津市', addr:'滋賀県草津市西渋川1-23-1 エイスクエア草津SARA北館2F', hours:'10:00〜19:00', closed:'不定休', price:'1〜2歳：平日600円・休日800円／3〜12歳：平日1,000円・休日1,200円',
    desc:'2024年4月オープン。巨大ジャングルジムやボールプール、乗り物など遊具がいっぱい。飲食物の持込OK・出入り自由が嬉しい。',
    sense:['🏗 施設感つよい','🔊 にぎやか','👶 抱っこでOK'],
    keywords:['巨大ジャングルジム','ボールプール','飲食持込OK','2024年オープン'],
    facilities:['駐車場あり','雨の日OK','おむつ替え','飲食可'],
    play:['巨大ジャングルジム','ボールプール','乗り物コーナー','フリープレイゲーム'],
    highlight:'飲食持込OKで出入り自由。ランチを持参してゆっくり過ごせる。2024年オープンで施設がきれい。',
    rating:4.1, galleryBg:'linear-gradient(135deg,#ffe8e8,#ffc8c8)',
    ageGroups:[0,1,2,3,4,5,6,7,8], lat:35.0123, lng:135.9312
  },
  {
    id:'crazy_bane', emoji:'🏠', name:'クレイジーバネット イオンモール草津店', cat:'室内遊び場', catClass:'indoor',
    loc:'草津市', addr:'滋賀県草津市新浜町300 イオンモール草津3F', hours:'10:00〜20:00', closed:'不定休', price:'1〜2歳：平日600円・休日800円／3〜12歳：平日1,000円・休日1,200円',
    desc:'2024年3月オープン。トランポリンやブロックタワー、手あそびハウスなど体を動かして遊べるアクティブゾーン。イオンモール内なので雨の日も安心。',
    sense:['🏗 施設感つよい','🔊 にぎやか','🏃 走り回れる'],
    keywords:['トランポリン','ブロックタワー','2024年オープン','イオンモール内'],
    facilities:['駐車場あり','雨の日OK','おむつ替え','授乳室'],
    play:['トランポリン','ブロックタワー','手あそびハウス','アクティブゾーン'],
    highlight:'2024年の新スポット。トランポリンで思いっきり跳び跳ねられる。買い物ついでに寄れる。',
    rating:4.0, galleryBg:'linear-gradient(135deg,#e8f0ff,#c0d4ff)',
    ageGroups:[1,2,3,4,5,6,7,8], lat:35.0212, lng:135.9534
  },
  {
    id:'zakids_konan', emoji:'🏠', name:'ザキッズ フレンドマート甲南店', cat:'室内遊び場', catClass:'indoor',
    loc:'甲賀市', addr:'滋賀県甲賀市甲南町寺庄地内 フレンドマート甲南店内', hours:'10:00〜19:00', closed:'不定休', price:'平日600円〜・休日800円〜',
    desc:'甲賀エリアの室内遊び場。0歳から遊べる全天候型。ビタミンカラーの施設内に幼児から小学生が楽しめる遊具がいっぱい。',
    sense:['🏗 施設感つよい','🔊 にぎやか','👶 抱っこでOK'],
    keywords:['全天候型','巨大ジャングルジム','ボールプール','0歳から'],
    facilities:['駐車場あり','雨の日OK','おむつ替え'],
    play:['巨大ジャングルジム','ボールプール','ふわふわ遊具','乗り物コーナー'],
    highlight:'甲賀エリアの貴重な室内遊び場。0歳から入れる。雨の日の定番スポット。',
    rating:3.9, galleryBg:'linear-gradient(135deg,#fff0e0,#ffe0c0)',
    ageGroups:[0,1,2,3,4,5,6,7], lat:34.9612, lng:136.1423
  },
  {
    id:'biwako_children_hall', emoji:'🏛', name:'びわこ学びの丘（大型児童館）', cat:'室内遊び場', catClass:'indoor',
    loc:'高島市', addr:'滋賀県高島市今津町今津1640', hours:'9:00〜17:00', closed:'月曜', price:'無料',
    desc:'琵琶湖畔にある大型児童館。「琵琶湖・水・風」をテーマに子どもたちが自ら遊びを創り出せる施設。室内工作体験や宿泊施設・キャンプ場も。',
    sense:['🌿 自然感あり','🔇 静かめ','🏃 走り回れる'],
    keywords:['無料','工作体験','琵琶湖畔','宿泊可能'],
    facilities:['駐車場あり','無料','おむつ替え','飲食可'],
    play:['工作体験','屋外アスレチック','琵琶湖を眺める','キャンプ場（宿泊可能）'],
    highlight:'無料で1日楽しめる。琵琶湖畔の最高のロケーション。宿泊もできる家族旅行にも使える。',
    rating:4.3, galleryBg:'linear-gradient(135deg,#c8e8f8,#a8cce8)',
    ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.4012, lng:136.0234
  },
  {
    id:'hikone_science', emoji:'🔭', name:'彦根市立図書館・湖東こどもセンター', cat:'室内遊び場', catClass:'indoor',
    loc:'彦根市', addr:'滋賀県彦根市日夏町4769', hours:'9:00〜17:00', closed:'月曜', price:'入館150円〜・未就学児無料',
    desc:'プラネタリウムや体験展示、プロジェクションマッピングが楽しめる体験型施設。未就学児専用キッズトンネルあり。小さい子から楽しめる。',
    sense:['🏗 施設感つよい','🔇 静かめ','🔊 にぎやか'],
    keywords:['プラネタリウム','プロジェクションマッピング','キッズトンネル','入館150円〜'],
    facilities:['駐車場あり','雨の日OK','おむつ替え','授乳室'],
    play:['プラネタリウム番組','体験展示','プロジェクションマッピング','キッズトンネル（未就学児専用）'],
    highlight:'コスパ最高。プラネタリウム番組は季節ごとに変わる。未就学児専用コーナーが嬉しい。',
    rating:4.2, galleryBg:'linear-gradient(135deg,#e8e8f8,#d0d0f0)',
    ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.2823, lng:136.2312
  },

  // ── カフェ・レストラン（追加）────────────────────
  {
    id:'michinoeki_aito', emoji:'🌼', name:'道の駅 あいとうマーガレットステーション', cat:'カフェ・レストラン', catClass:'cafe',
    loc:'東近江市', addr:'滋賀県東近江市愛東町布施323-1', hours:'9:00〜18:00', closed:'月曜', price:'食事700円〜',
    desc:'地元直売品やお土産が充実した道の駅。レストランでは地元野菜を使った料理が楽しめる。広い芝生広場でピクニックもできる。',
    sense:['🌿 自然感あり','🔇 静かめ','👶 抱っこでOK'],
    keywords:['地元野菜ランチ','道の駅','直売所','芝生広場'],
    facilities:['駐車場あり','飲食可','おむつ替え','ベビーカーOK'],
    play:['地元産野菜ランチ','直売所でお買い物','芝生広場でピクニック'],
    highlight:'地元野菜がふんだんに使われたランチが美味しい。直売所でお土産も買える。',
    rating:4.0, galleryBg:'linear-gradient(135deg,#f8f0d8,#f0e0b0)',
    ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.1134, lng:136.2012
  },
  {
    id:'ekimachi_nagahama', emoji:'🐟', name:'えきまちテラス長浜（長浜水族館）', cat:'カフェ・レストラン', catClass:'cafe',
    loc:'長浜市', addr:'滋賀県長浜市北船町3-50', hours:'10:00〜19:00', closed:'不定休', price:'入場無料（水族館）',
    desc:'長浜駅直結の複合施設。入場無料の水族館が目玉で、琵琶湖の生き物が展示されている。カフェやショップも充実。雨の日でも楽しめる。',
    sense:['🏗 施設感つよい','🔊 にぎやか','👶 抱っこでOK'],
    keywords:['入場無料水族館','長浜駅直結','琵琶湖の生き物','雨の日OK'],
    facilities:['駐車場あり','雨の日OK','おむつ替え','授乳室','飲食可'],
    play:['無料水族館見学','ショッピング','カフェでひと休み','長浜観光とセット'],
    highlight:'水族館が無料なのに充実。長浜駅すぐで雨の日に最適。長浜城・黒壁スクエアとセットで楽しめる。',
    rating:4.2, galleryBg:'linear-gradient(135deg,#d0e8f8,#b0cce8)',
    ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.3812, lng:136.2745
  },

  // ── ミュージアム・体験（追加）────────────────────
  {
    id:'omihachiman_water', emoji:'🚣', name:'近江八幡水郷めぐり', cat:'ミュージアム・体験', catClass:'museum',
    loc:'近江八幡市', addr:'滋賀県近江八幡市北之庄町880', hours:'9:00〜15:00（要予約）', closed:'不定休', price:'大人3,500円〜・3歳以下無料',
    desc:'手漕ぎの舟で水郷を巡る風情豊かな体験。葦が茂る水路を静かに進む体験は非日常的で記憶に残る。春の桜シーズンは特に美しい。',
    sense:['🌿 自然感あり','🔇 静かめ','👶 抱っこでOK'],
    keywords:['手漕ぎ舟','水郷めぐり','葦の水路','春の桜シーズン'],
    facilities:['駐車場あり'],
    play:['手漕ぎ舟体験','水郷の自然観察','野鳥観察','春の桜・葦の景色'],
    highlight:'3歳以下無料。子どもにとって舟に乗る体験は特別な思い出になる。ガイドさんの説明が面白い。',
    rating:4.4, galleryBg:'linear-gradient(135deg,#d8f0e8,#b8dcd0)',
    ageGroups:[1,2,3,4,5,6,7,8,9,10], lat:35.1289, lng:136.0934
  },
  {
    id:'grand_snow', emoji:'⛷', name:'グランスノー奥伊吹（奥伊吹スキー場）', cat:'ミュージアム・体験', catClass:'museum',
    loc:'米原市', addr:'滋賀県米原市甲津原奥伊吹', hours:'8:00〜17:00（シーズン中）', closed:'シーズン中無休', price:'入場無料・駐車場平日500円・休日1,000円',
    desc:'西日本最速・最長シーズンのスキー場。入場無料で駐車場代だけで1日雪遊びを満喫できる。幼児が屋内で遊べるコーナーもあり安心。',
    sense:['🌿 自然感あり','🔊 にぎやか','🏃 走り回れる'],
    keywords:['スキー・スノーボード','雪遊び','入場無料','幼児屋内コーナー'],
    facilities:['駐車場あり','飲食可','おむつ替え'],
    play:['スキー・スノーボード','ソリ遊び','雪遊びエリア','幼児屋内プレイコーナー'],
    highlight:'入場無料で駐車場代だけで雪遊びができる。幼児コーナーがあるので小さい子でも安心。',
    rating:4.2, galleryBg:'linear-gradient(135deg,#e8f0f8,#d0e0f0)',
    ageGroups:[1,2,3,4,5,6,7,8,9,10], lat:35.4123, lng:136.4012,
    phone:'0749-55-0123', officialUrl:'https://www.okuibuki.co.jp/'
  },
  {
    id:'nagahama_roman', emoji:'🏺', name:'黒壁スクエア（ガラス体験）', cat:'ミュージアム・体験', catClass:'museum',
    loc:'長浜市', addr:'滋賀県長浜市元浜町12-38', hours:'10:00〜17:00', closed:'不定休', price:'ガラス体験1,500円〜',
    desc:'長浜の観光名所・黒壁スクエアでガラス細工の手作り体験ができる。サンドブラストやガラス絵付けなど子どもでも楽しめるコースあり。',
    sense:['🏗 施設感つよい','🔇 静かめ','🏃 走り回れる'],
    keywords:['ガラス体験','サンドブラスト','絵付け体験','長浜観光'],
    facilities:['駐車場あり','雨の日OK'],
    play:['ガラス絵付け体験','サンドブラスト体験','黒壁スクエア散策','お土産ショッピング'],
    highlight:'子どもでも楽しめる体験コースがある。作った作品をお土産に持ち帰れる。長浜観光とセット。',
    rating:4.3, galleryBg:'linear-gradient(135deg,#f0e8f8,#e0d0f0)',
    ageGroups:[3,4,5,6,7,8,9,10], lat:35.3823, lng:136.2712,
    officialUrl:'https://www.kurokabe.co.jp/'
  },

  // ── ご飯・レストラン（子連れ個室・キッズスペースあり）────────────
  {
    id:'lobby_garden', emoji:'🍽', name:'LOBBY GARDEN by SKY TERRACE', cat:'ご飯・レストラン', catClass:'restaurant',
    loc:'草津市', addr:'滋賀県草津市大路2丁目1-25 近鉄百貨店草津店内', hours:'11:00〜21:00', closed:'不定休', price:'ランチ1,500円〜',
    desc:'2024年4月オープン。ベビーフェイスプラネッツが手掛けるホテルのような内観のレストラン。ドリンクバー付きで子連れランチに最適。緑あふれる空間でゆったり過ごせる。',
    sense:['🏗 施設感つよい','🔇 静かめ','👶 抱っこでOK'],
    keywords:['ドリンクバー','ホテルライクな内装','近鉄百貨店内','2024年オープン'],
    facilities:['駐車場あり','雨の日OK','おむつ替え','授乳室','子どもイス','飲食可'],
    play:['ドリンクバーでゆっくり','ショッピングとセット'],
    highlight:'2024年の新スポット。ドリンクバー付きで子どもも嬉しい。近鉄百貨店内なので雨でも安心。授乳室完備。',
    dogInfo: null,
    kidsSpace: true, privateRoom: false,
    rating:4.1, galleryBg:'linear-gradient(135deg,#e8f8e8,#c8f0c8)',
    ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:34.9912, lng:135.9223
  },
  {
    id:'hat_kitchen', emoji:'🍽', name:'ハットキッチン', cat:'ご飯・レストラン', catClass:'restaurant',
    loc:'湖南市', addr:'滋賀県湖南市中央1丁目1-1', hours:'11:00〜15:00', closed:'月・火曜', price:'ランチ1,000円〜',
    desc:'全面ガラス張りの開放感ある明るい店内。ベビーカーも通れる広さで子連れランチに最適。蜂蜜不使用の台湾カステラや無添加離乳食も取り扱い。',
    sense:['🏗 施設感つよい','🔇 静かめ','👶 抱っこでOK'],
    keywords:['ベビーカーOK','無添加離乳食','開放的な店内','地元野菜'],
    facilities:['駐車場あり','おむつ替え','ベビーカーOK','子どもイス'],
    play:['物産コーナー'],
    highlight:'ベビーカーで入れる広い店内。無添加離乳食が買えるのが嬉しい。子連れに優しい雰囲気。',
    dogInfo: null,
    kidsSpace: false, privateRoom: false,
    rating:4.2, galleryBg:'linear-gradient(135deg,#f8f0e0,#f0e4c0)',
    ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:34.9634, lng:136.0812
  },
  {
    id:'orisaki_restaurant', emoji:'🍽', name:'レストラン おりひめ（長浜）', cat:'ご飯・レストラン', catClass:'restaurant',
    loc:'長浜市', addr:'滋賀県長浜市神照町（国道8号沿い）', hours:'11:00〜21:00', closed:'不定休', price:'ランチ1,000円〜',
    desc:'北陸道長浜IC近くの独立系ファミリーレストラン。御膳・定食が充実しメニューが豊富。お子様メニューが充実していて家族連れに人気。好みがバラバラでも安心。',
    sense:['🏗 施設感つよい','🔊 にぎやか','👶 抱っこでOK'],
    keywords:['子どもメニュー充実','御膳・定食','ファミリーレストラン','長浜IC近く'],
    facilities:['駐車場あり','子どもイス','飲食可'],
    play:['充実した子どもメニュー'],
    highlight:'ご当地ファミレス。子どもメニューが豊富で迷うほど。御膳のおかわり自由が嬉しい。',
    dogInfo: null,
    kidsSpace: false, privateRoom: false,
    rating:4.0, galleryBg:'linear-gradient(135deg,#fce8e0,#f8d4c0)',
    ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.3712, lng:136.2534
  },
  {
    id:'whats_lifestyle', emoji:'🍽', name:"What's The Life Style（大津）", cat:'ご飯・レストラン', catClass:'restaurant',
    loc:'大津市', addr:'滋賀県大津市打出浜14-30 Oh!Me大津テラス内', hours:'11:00〜21:00', closed:'不定休', price:'ランチ1,200円〜',
    desc:'大津市のカフェレストラン。ナチュラルなSlow Floorとアートフロアの2フロア構成。Oh!Me大津テラス内なのでベビーカーでそのまま入れる。授乳室・おむつ替え完備。',
    sense:['🏗 施設感つよい','🔇 静かめ','👶 抱っこでOK'],
    keywords:['Oh!Me大津テラス内','ベビーカーOK','ナチュラル内装','子どもイス'],
    facilities:['駐車場あり','おむつ替え','授乳室','ベビーカーOK','子どもイス','雨の日OK'],
    play:['ショッピングモール内で買い物とセット'],
    highlight:'モール内なのでアクセス抜群。授乳室がすぐ近く。ベビーカーOKで安心。',
    dogInfo: null,
    kidsSpace: false, privateRoom: false,
    rating:4.0, galleryBg:'linear-gradient(135deg,#f0e8f8,#e0d8f0)',
    ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.0145, lng:135.8623
  },
  {
    id:'pizza_nagahama', emoji:'🍕', name:'ピッツェリア 近江八幡テラス', cat:'ご飯・レストラン', catClass:'restaurant',
    loc:'近江八幡市', addr:'滋賀県近江八幡市北之庄町', hours:'11:30〜21:00', closed:'火曜', price:'ピザ1,500円〜',
    desc:'全席150席の大型ピッツァ屋。イタリアから輸入した窯で焼くナポリピッツァが本格派。3階まであるフロアと1・2階テラスでBBQも。子ども連れ大歓迎。',
    sense:['🌿 自然感あり','🔊 にぎやか','🏃 走り回れる'],
    keywords:['本格ナポリピッツァ','テラスBBQ','3フロア','150席大型店'],
    facilities:['駐車場あり','子どもイス','飲食可','テラス席'],
    play:['本格ピザ体験','テラスBBQ'],
    highlight:'子どもが喜ぶ本格ピザ。テラスでBBQもできる。大型店なので待ち時間が少ない。',
    dogInfo: { allowed: 'テラス席のみOK', size: '全犬種', notes: 'テラスBBQ時も同伴可' },
    kidsSpace: false, privateRoom: false,
    rating:4.1, galleryBg:'linear-gradient(135deg,#fce8d8,#f8d0b8)',
    ageGroups:[1,2,3,4,5,6,7,8,9,10], lat:35.1289, lng:136.0712
  },

  // ── 犬連れOK（子連れ＋犬連れ両対応）────────────────────
  {
    id:'nagisa_warms', emoji:'🐕', name:'なぎさWARMS（なぎさテラス）', cat:'犬連れOK', catClass:'dog',
    loc:'大津市', addr:'滋賀県大津市打出浜15-5', hours:'11:00〜17:00', closed:'木・金曜', price:'ランチ1,000円〜',
    desc:'石場駅から徒歩3分の琵琶湖畔カフェ。テラス席から琵琶湖と比叡山を一望。なぎさテラス内の4店舗全てがテラス席犬同伴OKという稀有なスポット。エッグベネディクトが人気。',
    sense:['🌿 自然感あり','🔇 静かめ','👶 抱っこでOK'],
    keywords:['琵琶湖テラス席','犬連れOK','エッグベネディクト','なぎさテラス'],
    facilities:['駐車場あり','テラス席','飲食可'],
    play:['琵琶湖沿い散歩','テラスでゆっくりランチ'],
    dogInfo: { allowed: 'テラス席のみ', size: '全犬種', notes: 'なぎさテラス4店舗すべてテラス犬OKで選択肢豊富' },
    kidsSpace: false, privateRoom: false,
    rating:4.2, galleryBg:'linear-gradient(135deg,#d0e8f8,#b0d0f0)',
    ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.0123, lng:135.8734
  },
  {
    id:'mori_no_ki', emoji:'🐕', name:'Cafe 森の木', cat:'犬連れOK', catClass:'dog',
    loc:'高島市', addr:'滋賀県高島市安曇川町西万木1070-1', hours:'11:00〜16:00', closed:'日・月曜', price:'ランチ1,000円〜',
    desc:'300坪の広大なドッグラン併設の隠れ家カフェ。店内も犬同伴OKで全犬種歓迎。地元旬の野菜を使った週替わり「森の木ランチ」が人気。琵琶湖から15分の自然豊かな立地。',
    sense:['🌿 自然感あり','🔇 静かめ','🏃 走り回れる'],
    keywords:['300坪ドッグラン','店内犬OKフルサイズ','週替わりランチ','全犬種'],
    facilities:['駐車場あり','飲食可'],
    play:['300坪ドッグランで思いっきり走らせる','週替わりランチ'],
    dogInfo: { allowed: '店内・テラス両方OK', size: '全犬種OK・大型犬も歓迎', notes: '300坪の広大なドッグラン無料' },
    kidsSpace: false, privateRoom: false,
    rating:4.3, galleryBg:'linear-gradient(135deg,#d8ecd8,#b8d8b8)',
    ageGroups:[1,2,3,4,5,6,7,8,9,10], lat:35.4212, lng:136.0023
  },
  {
    id:'horicafe', emoji:'🐕', name:'ほりかふぇ（近江八幡）', cat:'犬連れOK', catClass:'dog',
    loc:'近江八幡市', addr:'滋賀県近江八幡市多賀町743', hours:'10:30〜16:00', closed:'水曜', price:'ランチ2,000円〜',
    desc:'時代劇ロケ地・八幡堀沿いの落ち着いた和風カフェレストラン。テラス席で犬同伴OK。近江牛や琵琶湖の天然魚など地元名産食材を使ったメニューが人気。',
    sense:['🌿 自然感あり','🔇 静かめ','👶 抱っこでOK'],
    keywords:['八幡堀沿い','和風カフェ','近江牛','テラス犬OK'],
    facilities:['駐車場あり','飲食可','テラス席'],
    play:['八幡堀沿い散歩とセット','近江牛ランチ'],
    dogInfo: { allowed: 'テラス席のみ', size: '全犬種', notes: '事前連絡推奨。八幡堀散歩とセットが◎' },
    kidsSpace: false, privateRoom: false,
    rating:4.3, galleryBg:'linear-gradient(135deg,#f0e8d8,#e0d4b8)',
    ageGroups:[1,2,3,4,5,6,7,8,9,10], lat:35.1278, lng:136.0934
  },
  {
    id:'rockbay', emoji:'🐕', name:'ROCK BAY GARDEN（道の駅草津）', cat:'犬連れOK', catClass:'dog',
    loc:'草津市', addr:'滋賀県草津市下物町1431', hours:'9:00〜15:00', closed:'月曜', price:'ランチ1,000円〜',
    desc:'道の駅草津に併設の体験農園カフェ。テラス席が犬同伴OKで、地元産野菜を使ったベジレストランMITASUが人気。いちご狩り（季節限定）とセットで楽しめる。',
    sense:['🌿 自然感あり','🔇 静かめ','👶 抱っこでOK'],
    keywords:['テラス犬OK','地元野菜ランチ','いちご狩り（春季）','道の駅草津'],
    facilities:['駐車場あり','飲食可','テラス席'],
    play:['いちご狩り（春季）','地元野菜ランチ','農園散策'],
    dogInfo: { allowed: 'テラス席のみ', size: '全犬種', notes: 'いちご狩りシーズン（春）は特に混む' },
    kidsSpace: false, privateRoom: false,
    rating:4.1, galleryBg:'linear-gradient(135deg,#e8f8d0,#d0f0b8)',
    ageGroups:[1,2,3,4,5,6,7,8,9,10], lat:35.0167, lng:135.9534,
    phone:'077-568-3078', officialUrl:'https://rockbaygarden.com/'
  },
  {
    id:'kusatsu_dogcafe', emoji:'🐕', name:'ドッグカフェ（草津市・ドッグラン120坪）', cat:'犬連れOK', catClass:'dog',
    loc:'草津市', addr:'滋賀県草津市野村2丁目22-8', hours:'10:00〜17:00', closed:'不定休', price:'カフェ500円〜',
    desc:'120坪のドッグランが併設され店内も犬OK。全犬種OKで入店料200円/1頭。犬のおもちゃや専用メニューあり。ドッグランを見ながらテラスでお茶を楽しめる。',
    sense:['🌿 自然感あり','🔊 にぎやか','🏃 走り回れる'],
    keywords:['120坪ドッグラン','店内犬OK','全犬種','犬用メニュー'],
    facilities:['駐車場あり','飲食可'],
    play:['120坪ドッグランで遊ぶ','犬用おもちゃで遊ぶ'],
    dogInfo: { allowed: '店内・テラス両方OK', size: '全犬種OK・大型犬歓迎', notes: '入店料200円/1頭。犬用メニューあり' },
    kidsSpace: false, privateRoom: false,
    rating:4.0, galleryBg:'linear-gradient(135deg,#f8f0d8,#f0e4b8)',
    ageGroups:[2,3,4,5,6,7,8,9,10], lat:35.0034, lng:135.9412
  },
  {
    id:'lamp_hakodate', emoji:'🐕', name:'パフェ専門店LAMP（びわこ箱館山）', cat:'犬連れOK', catClass:'dog',
    loc:'高島市', addr:'滋賀県高島市今津町日置前807（びわこ箱館山内）', hours:'ゴンドラ営業時間に準ずる', closed:'不定休', price:'パフェ1,000円〜',
    desc:'標高680mの山頂にある山小屋風パフェ専門店。犬はリード着用でゴンドラ乗車可（ケージ不要）。テラス席犬OK。近くに無料ドッグランあり（小型・大型の2区画）。',
    sense:['🌿 自然感あり','🔇 静かめ','🏃 走り回れる'],
    keywords:['山頂パフェ','犬ゴンドラ乗車可','無料ドッグラン','びわこ箱館山'],
    facilities:['駐車場あり','飲食可'],
    play:['ゴンドラで犬と山頂へ','無料ドッグラン','山頂パフェ'],
    dogInfo: { allowed: 'テラス席OK・ゴンドラも乗車可', size: '全犬種OK（ケージ不要・リード着用）', notes: '無料ドッグラン2区画（小型・大型別）あり' },
    kidsSpace: false, privateRoom: false,
    rating:4.4, galleryBg:'linear-gradient(135deg,#e8e0f8,#d0c8f0)',
    ageGroups:[2,3,4,5,6,7,8,9,10], lat:35.4123, lng:136.0234
  },

  // ═══════ 彦根エリア（滋賀） ═══════
  {
    id:'hikonejo', emoji:'🏯', name:'彦根城', cat:'ミュージアム・体験', catClass:'museum',
    pref:'滋賀', loc:'彦根市', addr:'滋賀県彦根市金亀町1-1', hours:'8:30〜17:00', closed:'なし', price:'一般800円 / 小中400円',
    desc:'国宝・彦根城。天守からの琵琶湖の眺めは絶景。ひこにゃんにも会えるかも。',
    keywords:['国宝天守','ひこにゃん','城下町','石垣','玄宮園'],
    play:['天守見学','ひこにゃん登場','玄宮園散策','お堀の白鳥','やぐら'],
    highlight:'ひこにゃん登場時間は公式でチェック。階段多めでベビーカーは下まで。城下町散策とセットがおすすめ。',
    rating:4.5, galleryBg:'linear-gradient(135deg,#e8d8b8,#d0b890)',
    ageGroups:[3,4,5,6,7,8,9,10], lat:35.2763, lng:136.2518
  },
  {
    id:'yumekyobashi', emoji:'🏘', name:'夢京橋キャッスルロード', cat:'カフェ・レストラン', catClass:'cafe',
    pref:'滋賀', loc:'彦根市', addr:'滋賀県彦根市本町2', hours:'店舗による', closed:'店舗による', price:'店舗による',
    desc:'彦根城前の江戸風城下町。白壁黒瓦の町並みで食べ歩きと散策が楽しい。',
    keywords:['城下町','食べ歩き','近江牛','和菓子','ひこどらやき'],
    play:['町並み散策','近江牛コロッケ','ひこどらやき','和菓子屋さん巡り'],
    highlight:'子連れでゆっくり散策できる。ベンチも多い。駐車場は彦根城の大手前駐車場が便利。',
    rating:4.3, galleryBg:'linear-gradient(135deg,#f0e0c8,#d8c0a0)',
    ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.2736, lng:136.2515
  },
  {
    id:'yonbancho', emoji:'🏮', name:'四番町スクエア', cat:'カフェ・レストラン', catClass:'cafe',
    pref:'滋賀', loc:'彦根市', addr:'滋賀県彦根市本町1-8', hours:'10:00〜18:00（店舗による）', closed:'店舗による', price:'無料',
    desc:'昭和レトロな広場。屋根付き商店街で雨の日も歩ける。お土産屋・カフェが集結。',
    keywords:['昭和レトロ','屋根付き','お土産','抹茶カフェ','近江屋'],
    play:['商店街散策','抹茶ソフト','地元野菜マルシェ','ひこねのりんご飴'],
    highlight:'雨の日でも楽しめる。小さな子どもも歩きやすい。ベンチ多めでおばあちゃん同伴でも安心。',
    rating:4.1, galleryBg:'linear-gradient(135deg,#e8dac8,#c8b598)',
    ageGroups:[0,1,2,3,4,5,6,7,8], lat:35.2728, lng:136.2494
  },
  {
    id:'kojinyama', emoji:'🌲', name:'荒神山自然の家', cat:'ミュージアム・体験', catClass:'museum',
    pref:'滋賀', loc:'彦根市', addr:'滋賀県彦根市清崎町1866', hours:'9:00〜17:00', closed:'月曜', price:'入園無料（体験別途）',
    desc:'アスレチック・キャンプ・自然体験ができる彦根市南部の森。',
    keywords:['アスレチック','キャンプ','自然体験','琵琶湖ビュー','展望台'],
    play:['森のアスレチック','ネイチャークラフト','展望台ハイキング','自然観察'],
    highlight:'予約制プログラムあり（要電話）。展望台からの琵琶湖の眺めが素晴らしい。',
    rating:4.2, galleryBg:'linear-gradient(135deg,#c8e0c0,#a0c898)',
    ageGroups:[3,4,5,6,7,8,9,10], lat:35.2334, lng:136.2197
  },
  {
    id:'hikone_kodomo', emoji:'🎨', name:'彦根市子どもセンター', cat:'室内遊び場', catClass:'indoor',
    pref:'滋賀', loc:'彦根市', addr:'滋賀県彦根市平田町670', hours:'9:00〜17:00', closed:'月曜・祝日翌日', price:'無料',
    desc:'雨の日も安心の屋内遊び場。おもちゃ図書館・工作コーナー・プレイルームあり。',
    keywords:['屋内','無料','工作','おもちゃ','雨の日OK'],
    play:['プレイルーム','おもちゃ図書館','工作コーナー','絵本コーナー'],
    highlight:'0歳から遊べる乳児コーナーあり。雨の日の定番。駐車場は隣接の市営利用。',
    rating:4.0, galleryBg:'linear-gradient(135deg,#e8d0e0,#c8a8c0)',
    ageGroups:[0,1,2,3,4,5,6], lat:35.2720, lng:136.2598
  },

  // ═══════ 福井エリア ═══════
  {
    id:'echizen_aquarium', emoji:'🐟', name:'越前松島水族館', cat:'ミュージアム・体験', catClass:'museum',
    pref:'福井', loc:'坂井市', addr:'福井県坂井市三国町崎74-2-3', hours:'9:00〜17:30', closed:'なし', price:'大人2,200円 / 小中1,100円 / 幼児600円',
    desc:'日本海を間近に望む水族館。ペンギンのお散歩やイルカショーが人気。触れる展示も多い。',
    keywords:['ペンギン','イルカショー','タッチプール','日本海','さんごの海'],
    play:['ペンギンお散歩','イルカショー','タッチプール','海の生き物観察'],
    highlight:'体験型展示が多く、小さい子も飽きない。日本海ビューの屋外展示も必見。',
    rating:4.4, galleryBg:'linear-gradient(135deg,#a8d8e8,#78b8d0)',
    ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:36.2420, lng:136.1427
  },
  {
    id:'tsuruga_redbrick', emoji:'🚂', name:'敦賀赤レンガ倉庫', cat:'ミュージアム・体験', catClass:'museum',
    pref:'福井', loc:'敦賀市', addr:'福井県敦賀市金ヶ崎町4-1', hours:'9:30〜17:30', closed:'水曜', price:'ジオラマ館400円',
    desc:'明治の赤レンガ倉庫をリノベ。ジオラマ館（鉄道＆街）とレストラン街。',
    keywords:['赤レンガ','鉄道ジオラマ','レストラン','港町','ノスタルジー'],
    play:['鉄道ジオラマ鑑賞','レストラン街','港散策','敦賀ムゼウム隣接'],
    highlight:'鉄道好きの子どもに刺さる。食事もできるので昼食込みで計画可能。',
    rating:4.2, galleryBg:'linear-gradient(135deg,#e8b098,#d08870)',
    ageGroups:[2,3,4,5,6,7,8,9,10], lat:35.6518, lng:136.0614
  },
  {
    id:'kehi_jingu', emoji:'⛩', name:'氣比神宮', cat:'ミュージアム・体験', catClass:'museum',
    pref:'福井', loc:'敦賀市', addr:'福井県敦賀市曙町11-68', hours:'5:00〜17:00', closed:'なし', price:'無料',
    desc:'北陸道総鎮守。日本三大木造大鳥居のひとつ。子連れでも落ち着いて参拝できる広い境内。',
    keywords:['神社','大鳥居','参拝','御朱印','静か'],
    play:['大鳥居くぐり','境内散策','御朱印','手水','亀の池'],
    highlight:'境内が広く、小さい子も歩きやすい。ベビーカーでも段差少なく進める。',
    rating:4.3, galleryBg:'linear-gradient(135deg,#d8c8a0,#b8a880)',
    ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.6504, lng:136.0719
  },
  {
    id:'angel_land', emoji:'🔭', name:'エンゼルランドふくい', cat:'ミュージアム・体験', catClass:'museum',
    pref:'福井', loc:'坂井市', addr:'福井県坂井市春江町東太郎丸3-1', hours:'9:30〜17:00', closed:'月曜', price:'大人400円 / 中学生以下無料',
    desc:'福井県児童科学館。科学体験・プラネタリウム・屋外ジップラインと大型遊具。',
    keywords:['科学館','プラネタリウム','ジップライン','大型遊具','無料エリアあり'],
    play:['科学体験','プラネタリウム','屋外ジップライン','ふわふわドーム'],
    highlight:'屋外のふわふわドームが子どもに大人気。プラネタリウムは要時間確認。食事持ち込みOK。',
    rating:4.5, galleryBg:'linear-gradient(135deg,#c8c0e8,#a098d0)',
    ageGroups:[2,3,4,5,6,7,8,9,10], lat:36.1667, lng:136.2547
  },
  {
    id:'obama_marina', emoji:'⚓', name:'マーメイドテラス（小浜）', cat:'カフェ・レストラン', catClass:'cafe',
    pref:'福井', loc:'小浜市', addr:'福井県小浜市川崎1-3-2', hours:'9:00〜17:00', closed:'火曜', price:'入場無料',
    desc:'小浜湾沿いのフィッシャーマンズワーフ。海鮮グルメと海辺散策が楽しめる。',
    keywords:['港','海鮮','遊覧船','フィッシャーマンズワーフ','海辺'],
    play:['港散策','海鮮ランチ','遊覧船','海風を浴びる'],
    highlight:'遊覧船もあり、海好きな子には特別感。海鮮ランチは日によって混雑するので早めに。',
    rating:4.0, galleryBg:'linear-gradient(135deg,#a8d0e0,#78a8c0)',
    ageGroups:[2,3,4,5,6,7,8,9,10], lat:35.4966, lng:135.7479
  },

  // ═══════ 三重エリア ═══════
  {
    id:'suzuka_park', emoji:'🏎', name:'鈴鹿サーキットパーク', cat:'ミュージアム・体験', catClass:'museum',
    pref:'三重', loc:'鈴鹿市', addr:'三重県鈴鹿市稲生町7992', hours:'10:00〜17:00（季節変動）', closed:'不定休', price:'入場1,600円〜（乗り物別）',
    desc:'サーキット併設の家族向けテーマパーク。カート・アトラクション・プールが充実。',
    keywords:['カート','アトラクション','プール','F1','モータースポーツ'],
    play:['キッズカート','子ども向けアトラクション','プール（夏）','おしごとたいけん'],
    highlight:'カートは身長制限あり要確認。早め来場がおすすめ。駐車場広め。',
    rating:4.4, galleryBg:'linear-gradient(135deg,#f0a0a0,#d07878)',
    ageGroups:[3,4,5,6,7,8,9,10], lat:34.8432, lng:136.5371
  },
  {
    id:'yokkaichi_sports', emoji:'⛰', name:'四日市スポーツランド', cat:'公園', catClass:'park',
    pref:'三重', loc:'四日市市', addr:'三重県四日市市桜町9868-37', hours:'9:00〜17:00', closed:'火曜', price:'大人320円 / 小中160円',
    desc:'大型アスレチック・ゴーカート・スライダーなど総合アミューズメントな森の公園。',
    keywords:['大型アスレチック','ゴーカート','スライダー','森','1日遊べる'],
    play:['アスレチックコース','ゴーカート','芝ソリすべり','森の散策'],
    highlight:'1日遊べる規模。水分多めに用意。弁当持参OK、屋内食事スペースあり。',
    rating:4.3, galleryBg:'linear-gradient(135deg,#b8d8a8,#90b080)',
    ageGroups:[3,4,5,6,7,8,9,10], lat:34.9734, lng:136.6125
  },
  {
    id:'iga_ninja', emoji:'🥷', name:'伊賀流忍者博物館', cat:'ミュージアム・体験', catClass:'museum',
    pref:'三重', loc:'伊賀市', addr:'三重県伊賀市上野丸之内117', hours:'9:30〜17:00', closed:'12/29〜1/1', price:'大人800円 / 小中500円',
    desc:'本物の忍者屋敷＋忍術実演ショー＋手裏剣体験。忍者好きにはたまらない。',
    keywords:['忍者屋敷','からくり','手裏剣','忍術ショー','伊賀'],
    play:['忍者屋敷見学','忍術実演ショー','手裏剣打ち体験','忍者衣装で記念撮影'],
    highlight:'忍術ショーは時間指定あり・別料金。手裏剣体験は子どもも楽しめる。',
    rating:4.3, galleryBg:'linear-gradient(135deg,#c0c0c0,#808080)',
    ageGroups:[4,5,6,7,8,9,10], lat:34.7693, lng:136.1309
  },
  {
    id:'nabana_sato', emoji:'🌸', name:'なばなの里', cat:'ミュージアム・体験', catClass:'museum',
    pref:'三重', loc:'桑名市', addr:'三重県桑名市長島町駒江漆畑270', hours:'10:00〜21:00（季節変動）', closed:'不定休', price:'大人2,500円（金券1,000円付）',
    desc:'四季の花とイルミネーションの里。子どもでも感動する規模の花畑とライトアップ。',
    keywords:['花畑','イルミネーション','チューリップ','四季','レストラン'],
    play:['花畑散策','イルミネーション鑑賞','アイランド富士（展望台）','園内レストラン'],
    highlight:'冬〜春のイルミ期間は激混。平日昼がおすすめ。広いのでベビーカー必須。',
    rating:4.4, galleryBg:'linear-gradient(135deg,#f0b8d0,#d088a8)',
    ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.1116, lng:136.6614
  },
  {
    id:'menard_aoyama', emoji:'🌿', name:'メナード青山リゾート', cat:'ミュージアム・体験', catClass:'museum',
    pref:'三重', loc:'伊賀市', addr:'三重県伊賀市霧生2356', hours:'10:00〜17:00（季節変動）', closed:'不定休', price:'ハーブガーデン500円',
    desc:'広大なハーブガーデンと体験教室。ラベンダー畑は夏の名物。子ども向けクラフトも。',
    keywords:['ハーブ','ラベンダー','体験教室','リゾート','高原'],
    play:['ハーブガーデン散策','ラベンダー摘み（夏）','クラフト体験','テラスカフェ'],
    highlight:'標高が高く夏でも涼しい。アクセスは車推奨。食事もリゾート内で完結。',
    rating:4.2, galleryBg:'linear-gradient(135deg,#d0c0e8,#a890c0)',
    ageGroups:[2,3,4,5,6,7,8,9,10], lat:34.6575, lng:136.1958
  },

  // ═══════ 滋賀拡張（大津・草津・守山・栗東・野洲・近江八幡・東近江・日野・竜王・長浜・米原・高島・多賀）═══════
  { id:'enryakuji', emoji:'⛩', name:'比叡山延暦寺', cat:'ミュージアム・体験', catClass:'museum', pref:'滋賀', loc:'大津市', addr:'滋賀県大津市坂本本町4220', hours:'8:30〜16:30', closed:'なし', price:'東塔・西塔・横川共通 1,000円', desc:'世界遺産の天台宗総本山。広大な山上境内で自然と歴史にふれる。', keywords:['世界遺産','天台宗','山','紅葉','自然'], play:['境内散策','根本中堂参拝','紅葉狩り','ケーブルカー'], highlight:'ケーブル利用が楽。歩くと広大なので子連れは電動カート推奨エリアも。', rating:4.5, galleryBg:'linear-gradient(135deg,#c0d8c0,#98b698)', ageGroups:[4,5,6,7,8,9,10], lat:35.0709, lng:135.8414 },
  { id:'miidera', emoji:'🏯', name:'三井寺（園城寺）', cat:'ミュージアム・体験', catClass:'museum', pref:'滋賀', loc:'大津市', addr:'滋賀県大津市園城寺町246', hours:'8:00〜17:00', closed:'なし', price:'大人600円 / 小中300円', desc:'長等山の広大な古刹。桜と紅葉が名所、境内も広く歩きやすい。', keywords:['古刹','桜','紅葉','弁慶の引き摺り鐘','境内散策'], play:['境内散策','桜見物','紅葉狩り','弁慶鐘'], highlight:'境内は広いが平坦な道も多くベビーカーOKな箇所あり。桜の時期は混雑。', rating:4.3, galleryBg:'linear-gradient(135deg,#e0d0b8,#c8b090)', ageGroups:[2,3,4,5,6,7,8,9,10], lat:35.0197, lng:135.8539 },
  { id:'ishiyamadera', emoji:'🏯', name:'石山寺', cat:'ミュージアム・体験', catClass:'museum', pref:'滋賀', loc:'大津市', addr:'滋賀県大津市石山寺1-1-1', hours:'8:00〜16:30', closed:'なし', price:'大人600円 / 小学生250円', desc:'紫式部ゆかりの古刹。多宝塔と石段、庭園が見どころ。', keywords:['紫式部','多宝塔','源氏物語','石段','境内'], play:['多宝塔','境内散策','源氏物語ゆかり','庭園'], highlight:'石段が多めなのでベビーカーは要注意。紫式部ゆかりの展示は小学生以上向き。', rating:4.3, galleryBg:'linear-gradient(135deg,#d8c8a8,#b8a888)', ageGroups:[4,5,6,7,8,9,10], lat:34.9614, lng:135.9033 },
  { id:'hanafunsui', emoji:'⛲', name:'びわ湖花噴水', cat:'公園', catClass:'park', pref:'滋賀', loc:'大津市', addr:'滋賀県大津市浜大津5', hours:'12:00〜14:00・18:00〜21:00（日による）', closed:'不定休', price:'無料', desc:'琵琶湖上の世界最大級の噴水ショー。大津港から観覧。', keywords:['噴水','琵琶湖','ライトアップ','大津港','ショー'], play:['噴水観覧','ライトアップ鑑賞','湖畔散歩'], highlight:'夜のライトアップが特にきれい。風が強いと中止の日もあるので要確認。', rating:4.2, galleryBg:'linear-gradient(135deg,#a0c8e0,#78a0c0)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.0100, lng:135.8700 },
  { id:'michigan', emoji:'🚢', name:'ミシガン（琵琶湖遊覧船）', cat:'ミュージアム・体験', catClass:'museum', pref:'滋賀', loc:'大津市', addr:'滋賀県大津市浜大津5-1-1', hours:'10:00〜17:00（便による）', closed:'なし', price:'60分コース大人2,500円〜', desc:'外輪船スタイルの琵琶湖遊覧船。ランチクルーズも人気。', keywords:['遊覧船','クルーズ','外輪船','琵琶湖','ランチ'], play:['船上散策','ランチクルーズ','湖上展望','記念撮影'], highlight:'予約推奨。子どもはデッキで楽しめる。ベビーカーもOK。', rating:4.3, galleryBg:'linear-gradient(135deg,#b0d0e8,#88a8c8)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.0100, lng:135.8700 },
  { id:'tachiki_jinja', emoji:'⛩', name:'立木神社', cat:'ミュージアム・体験', catClass:'museum', pref:'滋賀', loc:'草津市', addr:'滋賀県草津市草津4-1-3', hours:'6:00〜18:00', closed:'なし', price:'無料', desc:'草津宿を見守る鹿の神社。七五三や初詣で賑わう。', keywords:['神社','七五三','鹿','草津宿','御朱印'], play:['参拝','御朱印','鹿みくじ'], highlight:'境内はコンパクトで小さい子も安心。七五三の時期は要予約。', rating:4.1, galleryBg:'linear-gradient(135deg,#d8c8b0,#b8a890)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:34.9972, lng:135.9598 },
  { id:'aeon_kusatsu', emoji:'🏢', name:'イオンモール草津', cat:'室内遊び場', catClass:'indoor', pref:'滋賀', loc:'草津市', addr:'滋賀県草津市新浜町300', hours:'10:00〜22:00', closed:'なし', price:'入場無料', desc:'キッズスペース、授乳室、フードコート完備の大型モール。', keywords:['ショッピング','キッズスペース','フードコート','雨の日OK'], play:['買い物','キッズスペース','フードコート','映画館'], highlight:'雨の日の定番。授乳室・おむつ替えスペース多数で安心。', rating:4.0, galleryBg:'linear-gradient(135deg,#d0d0d8,#b0b0b8)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.0080, lng:135.9653 },
  { id:'biwako_museum', emoji:'🐟', name:'琵琶湖博物館', cat:'ミュージアム・体験', catClass:'museum', pref:'滋賀', loc:'草津市', addr:'滋賀県草津市下物町1091', hours:'9:30〜17:00', closed:'月曜', price:'大人800円 / 高大生450円 / 中学生以下無料', desc:'琵琶湖の生き物と歴史を学べる体験型博物館。巨大水槽が圧巻。', keywords:['水族館','博物館','琵琶湖','淡水魚','体験展示'], play:['水族館見学','体験展示','巨大ビワコオオナマズ','歴史展示'], highlight:'中学生以下無料はありがたい。1日遊べる規模。ベビーカーOK。', rating:4.5, galleryBg:'linear-gradient(135deg,#a8d0e8,#80a8c8)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.0875, lng:135.9350 },
  { id:'rokuha', emoji:'🌳', name:'ロクハ公園', cat:'公園', catClass:'park', pref:'滋賀', loc:'草津市', addr:'滋賀県草津市追分7丁目1-1', hours:'常時開放（プールは夏季9:00-17:00）', closed:'なし', price:'入園無料（プール別途）', desc:'大型遊具とじゃぶじゃぶ池、夏のプールが人気の総合公園。', keywords:['大型遊具','プール','じゃぶじゃぶ池','芝生','駐車場無料'], play:['大型遊具','じゃぶじゃぶ池（夏）','プール（夏季）','芝生広場'], highlight:'夏のプールは混雑するので朝イチ推奨。駐車場は無料で大型。', rating:4.3, galleryBg:'linear-gradient(135deg,#c8e0c0,#a0c898)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:34.9994, lng:135.9333 },
  { id:'pieri_moriyama', emoji:'🏬', name:'ピエリ守山', cat:'室内遊び場', catClass:'indoor', pref:'滋賀', loc:'守山市', addr:'滋賀県守山市今浜町2620-5', hours:'10:00〜20:00（店舗による）', closed:'店舗による', price:'入場無料', desc:'琵琶湖畔の大型商業施設。プールやフードコートもある。', keywords:['ショッピング','フードコート','プール','琵琶湖','雨の日'], play:['買い物','フードコート','ゲームセンター','眺望'], highlight:'琵琶湖ビューが素敵。レストラン街でゆっくり食事可能。', rating:4.0, galleryBg:'linear-gradient(135deg,#c8d8e0,#a0b0c0)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.1231, lng:135.9744 },
  { id:'nagisa_nanohana', emoji:'🌼', name:'第一なぎさ公園（菜の花）', cat:'公園', catClass:'park', pref:'滋賀', loc:'守山市', addr:'滋賀県守山市今浜町地先', hours:'常時開放', closed:'なし', price:'無料', desc:'琵琶湖を背景に早春の菜の花畑が広がる絶景スポット。', keywords:['菜の花','琵琶湖','絶景','写真映え','春'], play:['菜の花鑑賞','湖畔散歩','写真撮影'], highlight:'1〜2月の菜の花の時期がベスト。駐車場は限られるので早朝推奨。', rating:4.4, galleryBg:'linear-gradient(135deg,#f0e0a0,#d8c880)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.1227, lng:135.9750 },
  { id:'ritto_shizen', emoji:'🌲', name:'栗東自然観察の森', cat:'公園', catClass:'park', pref:'滋賀', loc:'栗東市', addr:'滋賀県栗東市荒張696', hours:'9:00〜17:00', closed:'月曜', price:'無料', desc:'里山の自然を体感できる観察の森。昆虫観察や木の実拾いが楽しい。', keywords:['自然観察','里山','昆虫','木の実','森'], play:['自然観察','虫取り','木の実拾い','ネイチャーウォーク'], highlight:'虫よけ必須。季節ごとの生き物がいて何度訪れても楽しめる。', rating:4.2, galleryBg:'linear-gradient(135deg,#c0d8b0,#98b088)', ageGroups:[3,4,5,6,7,8,9,10], lat:34.9773, lng:135.9946 },
  { id:'alplaza_ritto', emoji:'🏢', name:'アルプラザ栗東', cat:'室内遊び場', catClass:'indoor', pref:'滋賀', loc:'栗東市', addr:'滋賀県栗東市綣2丁目3-22', hours:'9:00〜21:00', closed:'なし', price:'入場無料', desc:'フードコートとキッズ広場のある地域密着型SC。', keywords:['SC','フードコート','キッズ','雨の日','買い物'], play:['買い物','フードコート','キッズ広場'], highlight:'駅近で便利。雨の日のランチ場所として重宝。', rating:3.9, galleryBg:'linear-gradient(135deg,#d8d8d0,#b8b8b0)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:34.9912, lng:136.0012 },
  { id:'mikamiyama', emoji:'⛰', name:'三上山（近江富士）', cat:'公園', catClass:'park', pref:'滋賀', loc:'野洲市', addr:'滋賀県野洲市三上', hours:'常時開放', closed:'なし', price:'無料', desc:'富士山型の美しい低山。子連れ登山の入門に最適。', keywords:['登山','低山','近江富士','眺望','ハイキング'], play:['登山','ハイキング','山頂からの眺望'], highlight:'往復2-3時間。水分・動きやすい靴必須。山頂は琵琶湖一望。', rating:4.3, galleryBg:'linear-gradient(135deg,#b8d0b0,#90a888)', ageGroups:[5,6,7,8,9,10], lat:35.0447, lng:136.0319 },
  { id:'ooiwayama', emoji:'🗿', name:'大岩山古墳群', cat:'ミュージアム・体験', catClass:'museum', pref:'滋賀', loc:'野洲市', addr:'滋賀県野洲市辻町', hours:'常時開放', closed:'なし', price:'無料', desc:'古代の銅鐸が出土した古墳群。歴史公園として整備。', keywords:['古墳','銅鐸','歴史','遺跡','公園'], play:['古墳見学','歴史散策','展望'], highlight:'野洲市歴史民俗博物館と合わせて訪問がおすすめ。', rating:3.9, galleryBg:'linear-gradient(135deg,#c8c0a8,#a0986*80)', ageGroups:[4,5,6,7,8,9,10], lat:35.0500, lng:136.0400 },
  { id:'hachimanbori', emoji:'🚤', name:'八幡堀', cat:'カフェ・レストラン', catClass:'cafe', pref:'滋賀', loc:'近江八幡市', addr:'滋賀県近江八幡市宮内町', hours:'散策自由', closed:'なし', price:'無料（船は別途）', desc:'八幡山城の堀跡に残る情緒ある水路。船で巡るのも風情がある。', keywords:['八幡堀','水路','散策','船めぐり','時代劇ロケ地'], play:['堀沿い散策','船めぐり','古建築写真','カフェ巡り'], highlight:'船は予約がベター。近くにパン屋・カフェも多い。', rating:4.4, galleryBg:'linear-gradient(135deg,#c0c8d0,#909aa8)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.1345, lng:136.0858 },
  { id:'lacollina', emoji:'🧁', name:'ラ コリーナ近江八幡', cat:'カフェ・レストラン', catClass:'cafe', pref:'滋賀', loc:'近江八幡市', addr:'滋賀県近江八幡市北之庄町615-1', hours:'9:00〜18:00', closed:'なし', price:'入場無料', desc:'たねやの本社敷地にあるバームクーヘンの聖地。景観も圧巻。', keywords:['たねや','バームクーヘン','景観','カフェ','子連れ'], play:['バームクーヘン','カステラ','カフェ','草屋根見学'], highlight:'広くて子連れでも快適。週末は激混。ランチも可能。', rating:4.5, galleryBg:'linear-gradient(135deg,#d8e0b8,#b0b890)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.1237, lng:136.0969 },
  { id:'chomeiji', emoji:'⛩', name:'長命寺', cat:'ミュージアム・体験', catClass:'museum', pref:'滋賀', loc:'近江八幡市', addr:'滋賀県近江八幡市長命寺町157', hours:'8:00〜17:00', closed:'なし', price:'無料', desc:'808段の石段で知られる古刹。山上からの琵琶湖展望が絶景。', keywords:['石段','808段','琵琶湖','絶景','古刹'], play:['石段登り','境内散策','眺望'], highlight:'石段はかなりキツい。小学生高学年以上推奨。上まで車でも行ける。', rating:4.1, galleryBg:'linear-gradient(135deg,#c0c8b0,#909888)', ageGroups:[6,7,8,9,10], lat:35.1620, lng:136.0620 },
  { id:'eigenji', emoji:'🍁', name:'永源寺', cat:'ミュージアム・体験', catClass:'museum', pref:'滋賀', loc:'東近江市', addr:'滋賀県東近江市永源寺高野町41', hours:'9:00〜16:00', closed:'なし', price:'大人500円 / 中学生以下無料', desc:'紅葉の名所として有名な禅寺。渓谷沿いの静かなお寺。', keywords:['紅葉','禅寺','渓谷','静か','中学生以下無料'], play:['紅葉狩り','境内散策','渓谷眺め'], highlight:'紅葉シーズン（11月）は激混、早朝推奨。それ以外は静か。', rating:4.3, galleryBg:'linear-gradient(135deg,#e8b898,#c89878)', ageGroups:[2,3,4,5,6,7,8,9,10], lat:35.0998, lng:136.2511 },
  { id:'aeon_higashiomi', emoji:'🏬', name:'イオンモール東近江', cat:'室内遊び場', catClass:'indoor', pref:'滋賀', loc:'東近江市', addr:'滋賀県東近江市八日市緑町26-8', hours:'10:00〜21:00', closed:'なし', price:'入場無料', desc:'キッズスペースと専門店街のある地域のSC。', keywords:['SC','キッズ','フードコート','雨の日'], play:['買い物','フードコート','キッズスペース'], highlight:'東近江エリアの雨の日避難所。駐車場無料。', rating:3.9, galleryBg:'linear-gradient(135deg,#d0d0d8,#b0b0b8)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.1189, lng:136.1553 },
  { id:'blumenohill', emoji:'🐑', name:'滋賀農業公園ブルーメの丘', cat:'公園', catClass:'park', pref:'滋賀', loc:'日野町', addr:'滋賀県蒲生郡日野町西大路843', hours:'9:30〜18:00（季節変動）', closed:'冬季水曜', price:'大人1,200円 / 4歳以上500円', desc:'動物ふれあい、アスレチック、パターゴルフのある農業公園。', keywords:['動物','ふれあい','アスレチック','パターゴルフ','ドイツ'], play:['動物ふれあい','アスレチック','パターゴルフ','パン作り体験'], highlight:'1日遊べる。お弁当持参OK。イベント開催日は要予約。', rating:4.3, galleryBg:'linear-gradient(135deg,#d8e8c0,#b0c098)', ageGroups:[1,2,3,4,5,6,7,8,9,10], lat:34.9870, lng:136.2420 },
  { id:'hino_matsuri', emoji:'🏮', name:'日野祭り資料館（近江日野商人館）', cat:'ミュージアム・体験', catClass:'museum', pref:'滋賀', loc:'日野町', addr:'滋賀県蒲生郡日野町大窪1011', hours:'9:30〜16:00', closed:'月曜', price:'大人300円 / 小中100円', desc:'近江商人の歴史と日野祭りを紹介する資料館。', keywords:['近江商人','日野祭り','歴史','民俗','資料館'], play:['資料見学','歴史展示','町並み散策'], highlight:'小規模だが内容は濃い。日野祭り（5月）に合わせて訪問もおすすめ。', rating:3.9, galleryBg:'linear-gradient(135deg,#d0c0a8,#a89880)', ageGroups:[5,6,7,8,9,10], lat:35.0244, lng:136.2524 },
  { id:'ryuo_outlet', emoji:'🛍', name:'三井アウトレットパーク 滋賀竜王', cat:'カフェ・レストラン', catClass:'cafe', pref:'滋賀', loc:'竜王町', addr:'滋賀県蒲生郡竜王町大字薬師字砂山1178-694', hours:'10:00〜20:00', closed:'不定休', price:'入場無料', desc:'広大な屋外型アウトレット。フードコート・遊び場も充実。', keywords:['アウトレット','ショッピング','フードコート','ブランド'], play:['ショッピング','フードコート','キッズコーナー','イベント'], highlight:'週末は激混。平日午前が穴場。授乳室・キッズスペース完備。', rating:4.1, galleryBg:'linear-gradient(135deg,#d8d0c0,#b0a898)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.1173, lng:136.1040 },
  { id:'kurokabe', emoji:'🏮', name:'黒壁スクエア', cat:'カフェ・レストラン', catClass:'cafe', pref:'滋賀', loc:'長浜市', addr:'滋賀県長浜市元浜町', hours:'店舗による', closed:'店舗による', price:'散策無料', desc:'ガラス工芸の街長浜の中心。レトロな町並みで食べ歩きが楽しい。', keywords:['ガラス工芸','町並み','食べ歩き','レトロ','カフェ'], play:['町並み散策','ガラス工房見学','食べ歩き','カフェ巡り'], highlight:'ガラス体験は要予約。週末混むが平日は静か。', rating:4.3, galleryBg:'linear-gradient(135deg,#c8c0b0,#988880)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.3849, lng:136.2658 },
  { id:'nagahama_rail', emoji:'🚂', name:'長浜鉄道スクエア', cat:'ミュージアム・体験', catClass:'museum', pref:'滋賀', loc:'長浜市', addr:'滋賀県長浜市北船町1-41', hours:'9:30〜17:00', closed:'なし', price:'大人300円 / 小学生150円', desc:'日本最古の駅舎と鉄道ジオラマ。鉄道好きの子に刺さる。', keywords:['鉄道','ジオラマ','最古の駅舎','SL','鉄道ファン'], play:['駅舎見学','ジオラマ鑑賞','SL見学','歴史展示'], highlight:'黒壁スクエアとセットで訪問しやすい立地。', rating:4.2, galleryBg:'linear-gradient(135deg,#d0c8b0,#a09890)', ageGroups:[2,3,4,5,6,7,8,9,10], lat:35.3823, lng:136.2687 },
  { id:'mizudori_station', emoji:'🦆', name:'道の駅 湖北みずどりステーション', cat:'カフェ・レストラン', catClass:'cafe', pref:'滋賀', loc:'長浜市', addr:'滋賀県長浜市湖北町今西1731-1', hours:'9:00〜18:00', closed:'なし', price:'入場無料', desc:'琵琶湖畔の道の駅。渡り鳥観察と地元グルメが楽しめる。', keywords:['道の駅','渡り鳥','琵琶湖','地元野菜','鴨鍋'], play:['渡り鳥観察','地元野菜買い','鴨鍋ランチ'], highlight:'冬は渡り鳥の時期。鴨料理は予約推奨。', rating:4.1, galleryBg:'linear-gradient(135deg,#b8c8d8,#8898a8)', ageGroups:[2,3,4,5,6,7,8,9,10], lat:35.4510, lng:136.2390 },
  { id:'samegai', emoji:'💧', name:'醒井水の宿駅・地蔵川', cat:'公園', catClass:'park', pref:'滋賀', loc:'米原市', addr:'滋賀県米原市醒井93', hours:'常時開放（梅花藻は5-8月）', closed:'なし', price:'無料', desc:'清流に咲く梅花藻で有名な水の町。夏の涼スポット。', keywords:['清流','梅花藻','水の町','涼','夏'], play:['清流散策','梅花藻鑑賞','水遊び','写真撮影'], highlight:'夏の梅花藻（7-8月）がベスト。水が冷たく涼しい。', rating:4.3, galleryBg:'linear-gradient(135deg,#b0d0d8,#88a8b0)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.3202, lng:136.3575 },
  { id:'ibuki', emoji:'⛰', name:'伊吹山', cat:'公園', catClass:'park', pref:'滋賀', loc:'米原市', addr:'滋賀県米原市上野', hours:'ドライブウェイ8:00〜20:00（季節変動）', closed:'冬季通行止', price:'ドライブウェイ3,140円', desc:'滋賀最高峰。山頂までドライブウェイで行ける。夏の花畑が見事。', keywords:['山','ドライブウェイ','花畑','展望','夏'], play:['山頂散策','花畑鑑賞','展望','軽登山'], highlight:'山頂は標高1377mで夏でも涼しい。子連れ登山は山頂駐車場からがおすすめ。', rating:4.4, galleryBg:'linear-gradient(135deg,#b8c8b0,#8098*80)', ageGroups:[4,5,6,7,8,9,10], lat:35.4183, lng:136.4053 },
  { id:'shirahige', emoji:'⛩', name:'白鬚神社', cat:'ミュージアム・体験', catClass:'museum', pref:'滋賀', loc:'高島市', addr:'滋賀県高島市鵜川215', hours:'参拝自由', closed:'なし', price:'無料', desc:'琵琶湖に浮かぶ鳥居が幻想的。近江最古の大社。', keywords:['鳥居','琵琶湖','神社','絶景','写真映え'], play:['参拝','鳥居見物','写真撮影','湖畔散歩'], highlight:'SNS映え鳥居。朝夕の光が特に美しい。国道沿いで駐車場混雑注意。', rating:4.4, galleryBg:'linear-gradient(135deg,#e0b098,#b88878)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.2769, lng:135.9472 },
  { id:'metasequoia', emoji:'🌲', name:'マキノ メタセコイア並木', cat:'公園', catClass:'park', pref:'滋賀', loc:'高島市', addr:'滋賀県高島市マキノ町蛭口〜牧野', hours:'常時開放', closed:'なし', price:'無料', desc:'500本のメタセコイアが2.4km続く並木道。四季で表情を変える。', keywords:['並木','メタセコイア','絶景','ドライブ','写真'], play:['並木ドライブ','散歩','写真撮影','自転車'], highlight:'紅葉（11月）、新緑（5-6月）、雪（1-2月）すべて絶景。道路沿いのため駐車マナーに注意。', rating:4.6, galleryBg:'linear-gradient(135deg,#c8d8b8,#90a888)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.3823, lng:136.0144 },
  { id:'taga_taisha', emoji:'⛩', name:'多賀大社', cat:'ミュージアム・体験', catClass:'museum', pref:'滋賀', loc:'多賀町', addr:'滋賀県犬上郡多賀町多賀604', hours:'8:00〜16:00', closed:'なし', price:'無料', desc:'延命長寿の神様として親しまれる大社。境内も広く子連れで参拝しやすい。', keywords:['神社','延命','長寿','大社','御朱印'], play:['参拝','御朱印','境内散策','絵馬'], highlight:'初詣は混雑。駐車場は広めで無料。', rating:4.3, galleryBg:'linear-gradient(135deg,#d8c0a0,#a89880)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.2277, lng:136.2927 },

  // ═══════ 福井拡張 ═══════
  { id:'tojinbo', emoji:'🌊', name:'東尋坊', cat:'公園', catClass:'park', pref:'福井', loc:'坂井市', addr:'福井県坂井市三国町安島', hours:'散策自由', closed:'なし', price:'無料（遊覧船別途）', desc:'日本海の荒波が刻んだ断崖絶景。遊覧船で海からも見られる。', keywords:['断崖','絶景','日本海','遊覧船','商店街'], play:['断崖散策','遊覧船','商店街食べ歩き','展望'], highlight:'子連れは柵から離して見学。強風の日注意。', rating:4.3, galleryBg:'linear-gradient(135deg,#a0b8c8,#7088a0)', ageGroups:[3,4,5,6,7,8,9,10], lat:36.2416, lng:136.1250 },
  { id:'maruokajo', emoji:'🏯', name:'丸岡城', cat:'ミュージアム・体験', catClass:'museum', pref:'福井', loc:'坂井市', addr:'福井県坂井市丸岡町霞町1-59', hours:'8:30〜17:00', closed:'なし', price:'大人450円 / 小中150円', desc:'現存12天守のひとつ。急な階段が体験できる貴重な木造天守。', keywords:['現存天守','城','木造','歴史','急階段'], play:['天守登閣','歴史展示','周辺散策'], highlight:'階段がかなり急。小学生以上推奨。天守最上部からの眺めは素晴らしい。', rating:4.1, galleryBg:'linear-gradient(135deg,#c8b898,#9888*78)', ageGroups:[5,6,7,8,9,10], lat:36.1500, lng:136.2722 },
  { id:'dinosaur_museum', emoji:'🦖', name:'福井県立恐竜博物館', cat:'ミュージアム・体験', catClass:'museum', pref:'福井', loc:'勝山市', addr:'福井県勝山市村岡町寺尾51-11', hours:'9:00〜17:00', closed:'第2・4水曜', price:'大人1,000円 / 高大800円 / 小中500円', desc:'国内最大級の恐竜博物館。迫力の全身骨格と発掘体験。', keywords:['恐竜','化石','博物館','発掘','勝山'], play:['恐竜展示','発掘体験','ジオラマ','ショップ'], highlight:'予約制日あり。発掘体験は別途申込。1日遊べる規模。', rating:4.6, galleryBg:'linear-gradient(135deg,#c0a888,#907860)', ageGroups:[2,3,4,5,6,7,8,9,10], lat:36.0754, lng:136.5272 },
  { id:'dinopark', emoji:'🦕', name:'かつやまディノパーク', cat:'公園', catClass:'park', pref:'福井', loc:'勝山市', addr:'福井県勝山市村岡町寺尾', hours:'9:00〜17:00', closed:'不定休', price:'大人700円 / 子ども600円', desc:'恐竜博物館隣の野外恐竜パーク。等身大の恐竜モデルが迫力。', keywords:['恐竜','野外','パーク','等身大','博物館併設'], play:['恐竜ウォーク','化石発掘体験','ジップライン'], highlight:'博物館と合わせて訪問推奨。屋外なので雨具必要。', rating:4.2, galleryBg:'linear-gradient(135deg,#b0c098,#88a070)', ageGroups:[2,3,4,5,6,7,8,9,10], lat:36.0743, lng:136.5303 },
  { id:'asakura', emoji:'🏯', name:'一乗谷朝倉氏遺跡', cat:'ミュージアム・体験', catClass:'museum', pref:'福井', loc:'福井市', addr:'福井県福井市城戸ノ内町', hours:'散策自由（資料館9:00-17:00）', closed:'資料館12/28-1/4', price:'無料（資料館大人210円）', desc:'戦国時代の城下町を再現した国の特別史跡。時代劇ロケ地にもなる。', keywords:['戦国','城下町','史跡','朝倉氏','時代劇'], play:['町並み散策','資料館見学','歴史体験'], highlight:'広いので歩きやすい靴で。桜と紅葉のシーズンが特に美しい。', rating:4.4, galleryBg:'linear-gradient(135deg,#c0b098,#988*7868)', ageGroups:[4,5,6,7,8,9,10], lat:36.0225, lng:136.2929 },
  { id:'echizen_togei', emoji:'🏺', name:'越前陶芸村', cat:'ミュージアム・体験', catClass:'museum', pref:'福井', loc:'越前町', addr:'福井県丹生郡越前町小曽原120-61', hours:'9:00〜17:00', closed:'月曜', price:'入園無料（体験別途）', desc:'日本六古窯のひとつ越前焼の総合施設。陶芸体験が人気。', keywords:['越前焼','陶芸','体験','古窯','文化'], play:['陶芸体験','博物館見学','公園散策','ショップ'], highlight:'陶芸体験は小学生以上推奨。予約推奨。', rating:4.2, galleryBg:'linear-gradient(135deg,#c8a898,#987868)', ageGroups:[5,6,7,8,9,10], lat:35.8556, lng:136.1844 },
  { id:'fukui_shizenshi', emoji:'🦌', name:'福井市立自然史博物館', cat:'ミュージアム・体験', catClass:'museum', pref:'福井', loc:'福井市', addr:'福井県福井市足羽上町147', hours:'9:00〜17:00', closed:'月曜', price:'大人100円 / 中学生以下無料', desc:'福井の自然と生物を学べる博物館。プラネタリウムも併設。', keywords:['自然史','博物館','プラネタリウム','生物','展示'], play:['展示見学','プラネタリウム','体験学習'], highlight:'コンパクトながら内容は充実。コスパ良好。', rating:4.0, galleryBg:'linear-gradient(135deg,#b8c8b0,#889888)', ageGroups:[3,4,5,6,7,8,9,10], lat:36.0625, lng:136.2221 },
  { id:'katsuyama_castle', emoji:'🏯', name:'勝山城博物館', cat:'ミュージアム・体験', catClass:'museum', pref:'福井', loc:'勝山市', addr:'福井県勝山市平泉寺町林毛谷', hours:'9:00〜17:00', closed:'水曜', price:'大人500円 / 小中200円', desc:'高さ57.8mの日本一の天守高さの模擬天守。展望も良い。', keywords:['城','博物館','天守','展望','勝山'], play:['城内見学','展望台','歴史展示'], highlight:'模擬天守だが規模大きく見応えあり。恐竜博物館とセットで。', rating:3.9, galleryBg:'linear-gradient(135deg,#d0c0a8,#a09080)', ageGroups:[4,5,6,7,8,9,10], lat:36.0611, lng:136.5153 },
  { id:'wakasa_marine', emoji:'🐠', name:'若狭湾 海浜自然センター', cat:'ミュージアム・体験', catClass:'museum', pref:'福井', loc:'若狭町', addr:'福井県三方上中郡若狭町世久見18-2', hours:'9:00〜17:00', closed:'月曜', price:'大人300円 / 小中100円', desc:'若狭湾の生き物と自然を学べる体験型施設。タッチプールあり。', keywords:['海','自然','タッチプール','体験','若狭湾'], play:['タッチプール','展示見学','磯観察','クラフト'], highlight:'海辺の体験ができる貴重なスポット。水着持参で磯遊びも。', rating:4.1, galleryBg:'linear-gradient(135deg,#a8c8d8,#7898a8)', ageGroups:[2,3,4,5,6,7,8,9,10], lat:35.6000, lng:135.9000 },
  { id:'kehi_matsubara', emoji:'🌲', name:'気比の松原', cat:'公園', catClass:'park', pref:'福井', loc:'敦賀市', addr:'福井県敦賀市松島町', hours:'常時開放', closed:'なし', price:'無料', desc:'日本三大松原のひとつ。広大な砂浜と松林、夏は海水浴も。', keywords:['松原','砂浜','海水浴','日本三大','散策'], play:['散策','海水浴（夏）','砂遊び','松林ウォーク'], highlight:'夏は海水浴で賑わう。それ以外の季節は静か。ピクニックにも。', rating:4.3, galleryBg:'linear-gradient(135deg,#c0c8a0,#90987*8)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.6527, lng:136.0531 },

  // ═══════ 三重拡張 ═══════
  { id:'ise_naiku', emoji:'⛩', name:'伊勢神宮 内宮（皇大神宮）', cat:'ミュージアム・体験', catClass:'museum', pref:'三重', loc:'伊勢市', addr:'三重県伊勢市宇治館町1', hours:'5:00〜18:00（季節変動）', closed:'なし', price:'無料', desc:'日本人の心のふるさと、日本で最も格式高い神社。', keywords:['伊勢神宮','内宮','神社','パワースポット','参拝'], play:['参拝','宇治橋','神楽殿','御朱印'], highlight:'早朝がベスト。駐車場は離れた場所から無料バスも。おかげ横丁併せて訪問。', rating:4.7, galleryBg:'linear-gradient(135deg,#d0c0a0,#a09080)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:34.4551, lng:136.7254 },
  { id:'ise_geku', emoji:'⛩', name:'伊勢神宮 外宮（豊受大神宮）', cat:'ミュージアム・体験', catClass:'museum', pref:'三重', loc:'伊勢市', addr:'三重県伊勢市豊川町279', hours:'5:00〜18:00（季節変動）', closed:'なし', price:'無料', desc:'衣食住の神様。内宮から先に参拝する習わし。', keywords:['伊勢神宮','外宮','神社','豊受','参拝'], play:['参拝','神楽殿','御朱印'], highlight:'内宮より空いている。駅から近く便利。内宮と合わせて1日コース。', rating:4.5, galleryBg:'linear-gradient(135deg,#c8b898,#987*868)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:34.4902, lng:136.7060 },
  { id:'okage_yokocho', emoji:'🍡', name:'おかげ横丁', cat:'カフェ・レストラン', catClass:'cafe', pref:'三重', loc:'伊勢市', addr:'三重県伊勢市宇治中之切町52', hours:'9:30〜17:30', closed:'なし', price:'散策無料', desc:'内宮前の江戸情緒あふれる商店街。食べ歩きとお土産の定番。', keywords:['商店街','食べ歩き','江戸','赤福','お土産'], play:['食べ歩き','赤福','焼き団子','お土産買い'], highlight:'週末激混。早朝か平日推奨。ベビーカーは混雑時困難。', rating:4.4, galleryBg:'linear-gradient(135deg,#d8b898,#a88*878)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:34.4568, lng:136.7220 },
  { id:'toba_aquarium', emoji:'🐬', name:'鳥羽水族館', cat:'ミュージアム・体験', catClass:'museum', pref:'三重', loc:'鳥羽市', addr:'三重県鳥羽市鳥羽3-3-6', hours:'9:00〜17:00', closed:'なし', price:'大人2,800円 / 小中1,600円 / 幼児800円', desc:'国内最多1200種の海の生き物。ジュゴンが見られる日本唯一の水族館。', keywords:['水族館','ジュゴン','ラッコ','アシカショー','1200種'], play:['海獣ショー','ジュゴン見学','タッチプール','ラッコ'], highlight:'駐車場大きめ。隣接のミキモト真珠島とセットで1日コース可能。', rating:4.5, galleryBg:'linear-gradient(135deg,#a8c8d8,#7898a8)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:34.4819, lng:136.8338 },
  { id:'shima_spain', emoji:'🏰', name:'志摩スペイン村', cat:'公園', catClass:'park', pref:'三重', loc:'志摩市', addr:'三重県志摩市磯部町坂崎', hours:'9:30〜17:00（季節変動）', closed:'不定休', price:'大人5,400円 / 小学生4,200円', desc:'スペインをテーマにしたテーマパーク。絶叫マシンから子ども向けまで。', keywords:['テーマパーク','絶叫マシン','スペイン','フラメンコ','リゾート'], play:['アトラクション','フラメンコショー','スペイン街','レストラン'], highlight:'小さい子向けエリアも充実。夏はプールもオープン。', rating:4.3, galleryBg:'linear-gradient(135deg,#f0c8a0,#c89878)', ageGroups:[2,3,4,5,6,7,8,9,10], lat:34.3442, lng:136.8736 },
  { id:'gozaisho', emoji:'🚠', name:'御在所ロープウエイ', cat:'ミュージアム・体験', catClass:'museum', pref:'三重', loc:'菰野町', addr:'三重県三重郡菰野町湯の山温泉', hours:'9:00〜17:00（季節変動）', closed:'水曜（夏冬は無休）', price:'大人往復2,600円 / 小学生1,300円', desc:'標高1,212mの御在所岳へ空中散歩。四季の眺望が絶景。', keywords:['ロープウエイ','山頂','眺望','四季','温泉'], play:['ロープウエイ','山頂散策','景色','スキー（冬）'], highlight:'冬は雪景色、春は新緑、秋は紅葉、夏は涼。湯の山温泉も近い。', rating:4.5, galleryBg:'linear-gradient(135deg,#c0c8a0,#889878)', ageGroups:[2,3,4,5,6,7,8,9,10], lat:35.0264, lng:136.4164 },
  { id:'matsusaka_jo', emoji:'🏯', name:'松阪城跡', cat:'ミュージアム・体験', catClass:'museum', pref:'三重', loc:'松阪市', addr:'三重県松阪市殿町', hours:'常時開放', closed:'なし', price:'無料', desc:'石垣だけが残る城跡。城下町散策と松阪牛グルメの拠点。', keywords:['城跡','石垣','松阪牛','城下町','桜'], play:['石垣散策','本居宣長記念館','城下町','松阪牛'], highlight:'春は桜が見事。松阪牛ランチと合わせて訪問。', rating:4.1, galleryBg:'linear-gradient(135deg,#b8a888,#88*7868)', ageGroups:[3,4,5,6,7,8,9,10], lat:34.5747, lng:136.5278 },
  { id:'futami_meoto', emoji:'🌊', name:'夫婦岩・二見興玉神社', cat:'ミュージアム・体験', catClass:'museum', pref:'三重', loc:'伊勢市', addr:'三重県伊勢市二見町江575', hours:'参拝自由', closed:'なし', price:'無料', desc:'夫婦岩で有名な神社。伊勢神宮参拝前の禊の地。', keywords:['夫婦岩','神社','海','禊','伊勢'], play:['夫婦岩見物','参拝','海辺散策','夕陽'], highlight:'日の出が特に美しい。伊勢神宮とセット参拝が伝統。', rating:4.3, galleryBg:'linear-gradient(135deg,#a8b8c8,#7888a8)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:34.4996, lng:136.7840 },
  { id:'akame48', emoji:'💧', name:'赤目四十八滝', cat:'公園', catClass:'park', pref:'三重', loc:'名張市', addr:'三重県名張市赤目町長坂861-1', hours:'8:30〜17:00', closed:'なし', price:'大人500円 / 小学生250円', desc:'渓谷沿いに48の滝が連なる名勝。ネイチャーウォークが楽しい。', keywords:['滝','渓谷','ネイチャー','サンショウウオ','ハイキング'], play:['滝めぐり','渓谷ウォーク','センター見学','忍者体験（隣接）'], highlight:'往復3時間程度。歩きやすい靴必須。夏は涼しい。', rating:4.5, galleryBg:'linear-gradient(135deg,#a0c0b0,#708890)', ageGroups:[4,5,6,7,8,9,10], lat:34.6472, lng:136.1461 },
  { id:'nagashima_spa', emoji:'🎢', name:'ナガシマスパーランド', cat:'公園', catClass:'park', pref:'三重', loc:'桑名市', addr:'三重県桑名市長島町浦安333', hours:'9:30〜17:00（季節変動）', closed:'不定休', price:'大人3,500円 / 小学生2,400円 / 幼児1,300円', desc:'日本最大級の遊園地。絶叫マシン40種以上と夏のジャンボ海水プール。', keywords:['遊園地','絶叫マシン','プール','ジェットコースター'], play:['アトラクション','ジャンボ海水プール（夏）','キッズタウン','花火'], highlight:'小さい子向けキッズタウンも充実。1日遊べる。夏は水着持参。', rating:4.5, galleryBg:'linear-gradient(135deg,#f0a8a8,#c87878)', ageGroups:[2,3,4,5,6,7,8,9,10], lat:35.0869, lng:136.7272 },
  { id:'seki_shuku', emoji:'🏮', name:'関宿（東海道）', cat:'カフェ・レストラン', catClass:'cafe', pref:'三重', loc:'亀山市', addr:'三重県亀山市関町中町', hours:'散策自由', closed:'なし', price:'無料', desc:'東海道の宿場町がそのまま残る国の重要伝統的建造物群。', keywords:['東海道','宿場町','町並み','伝統','歴史'], play:['町並み散策','資料館','和菓子','カフェ'], highlight:'小規模だが時代タイムスリップ感。ベビーカーOK。', rating:4.3, galleryBg:'linear-gradient(135deg,#d0b898,#a08878)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:34.8581, lng:136.4161 },
  { id:'mokumoku', emoji:'🐷', name:'伊賀の里モクモク手づくりファーム', cat:'公園', catClass:'park', pref:'三重', loc:'伊賀市', addr:'三重県伊賀市西湯舟3609', hours:'10:00〜17:00', closed:'不定休', price:'大人1,100円 / 小学生800円 / 3歳以上500円', desc:'地元野菜・ハム作り体験・動物ふれあいの体験型農場。', keywords:['農場','ハム作り','動物ふれあい','野菜','体験'], play:['動物ふれあい','ハム作り体験','野菜狩り','農場レストラン'], highlight:'体験プログラムは予約必須。バーベキューも人気。', rating:4.4, galleryBg:'linear-gradient(135deg,#c8d8b0,#909888)', ageGroups:[1,2,3,4,5,6,7,8,9,10], lat:34.8000, lng:136.1833 },
  { id:'aquaignis', emoji:'♨', name:'アクアイグニス', cat:'カフェ・レストラン', catClass:'cafe', pref:'三重', loc:'菰野町', addr:'三重県三重郡菰野町大羽根園松ケ枝町', hours:'10:00〜22:00', closed:'なし', price:'温泉大人600円 / カフェは別途', desc:'温泉・レストラン・スイーツ・農園が集まる総合複合施設。', keywords:['温泉','スイーツ','レストラン','複合施設','菰野'], play:['日帰り温泉','スイーツ','地産レストラン','ベーカリー'], highlight:'辻口博啓のスイーツが人気。御在所ロープウェイとセットも可能。', rating:4.3, galleryBg:'linear-gradient(135deg,#d8c0a8,#a89088)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:34.9389, lng:136.5244 },
  { id:'yokkaichi_port', emoji:'🌃', name:'四日市港ポートビル（うみてらす14）', cat:'ミュージアム・体験', catClass:'museum', pref:'三重', loc:'四日市市', addr:'三重県四日市市霞2-1-1', hours:'10:00〜17:00', closed:'月曜', price:'大人310円 / 小中150円', desc:'工場夜景で有名な四日市の港展望施設。夜は絶景。', keywords:['工場夜景','展望台','港','四日市','夜景'], play:['展望','工場夜景','コンビナート展望','ミニシアター'], highlight:'夕方〜夜がベスト。工場夜景は日本夜景遺産。', rating:4.1, galleryBg:'linear-gradient(135deg,#9098b0,#606878)', ageGroups:[4,5,6,7,8,9,10], lat:34.9640, lng:136.6325 },
  { id:'mikimoto', emoji:'🦪', name:'ミキモト真珠島', cat:'ミュージアム・体験', catClass:'museum', pref:'三重', loc:'鳥羽市', addr:'三重県鳥羽市鳥羽1-7-1', hours:'9:00〜17:00', closed:'なし', price:'大人1,650円 / 小中800円', desc:'真珠養殖発祥の地。海女実演と真珠博物館がある。', keywords:['真珠','海女','博物館','鳥羽','実演'], play:['海女実演','真珠博物館','真珠ジュエリー','眺望'], highlight:'海女実演は時間指定あり。鳥羽水族館と合わせて1日コース。', rating:4.2, galleryBg:'linear-gradient(135deg,#d8c8d0,#a89890)', ageGroups:[4,5,6,7,8,9,10], lat:34.4872, lng:136.8353 },
  { id:'sakakibara', emoji:'♨', name:'榊原温泉', cat:'カフェ・レストラン', catClass:'cafe', pref:'三重', loc:'津市', addr:'三重県津市榊原町', hours:'店舗による', closed:'店舗による', price:'日帰り1,000円前後', desc:'清少納言の枕草子にも載る古湯。家族風呂のある旅館も。', keywords:['温泉','古湯','家族風呂','清少納言','日帰り'], play:['日帰り入浴','家族風呂','湯めぐり','周辺散策'], highlight:'家族風呂を選べば小さい子と安心。肌に優しい湯質。', rating:4.2, galleryBg:'linear-gradient(135deg,#d8c0c8,#a09098)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:34.7181, lng:136.3781 },
  { id:'tsu_kairakuen', emoji:'🌳', name:'津偕楽公園', cat:'公園', catClass:'park', pref:'三重', loc:'津市', addr:'三重県津市広明町', hours:'常時開放', closed:'なし', price:'無料', desc:'津藩主の別邸跡を公園化。桜と鉄道展示で地元に親しまれる。', keywords:['公園','桜','鉄道展示','散策','津市'], play:['散策','桜見物','鉄道展示','ベンチでのんびり'], highlight:'桜の季節（4月上旬）がベスト。駅近でアクセス良好。', rating:3.9, galleryBg:'linear-gradient(135deg,#f0c8d0,#c0a0a8)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:34.7322, lng:136.5081 },
  { id:'suzuka_mori', emoji:'🌸', name:'鈴鹿の森庭園', cat:'公園', catClass:'park', pref:'三重', loc:'鈴鹿市', addr:'三重県鈴鹿市山本町151', hours:'9:00〜16:00（開園期のみ）', closed:'開園期外', price:'大人1,000円〜 / 小中500円〜（時期変動）', desc:'しだれ梅200本の梅林。3月の開花時期のみ公開。', keywords:['しだれ梅','梅林','春','写真映え','開花時期限定'], play:['梅林散策','ライトアップ','写真撮影'], highlight:'3月の開花期のみ。夕方のライトアップが特に美しい。', rating:4.5, galleryBg:'linear-gradient(135deg,#f0c0d0,#c09098)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:34.9014, lng:136.4867 },
  { id:'nagashima_spa_ami', emoji:'♨', name:'湯あみの島（長島温泉）', cat:'室内遊び場', catClass:'indoor', pref:'三重', loc:'桑名市', addr:'三重県桑名市長島町浦安333', hours:'9:30〜23:00', closed:'不定休', price:'大人1,650円 / 小学生1,100円 / 幼児600円', desc:'17種の露天風呂・内湯が楽しめる大型温泉施設。', keywords:['温泉','露天風呂','スパ','長島','家族風呂'], play:['露天風呂','サウナ','岩盤浴','キッズエリア'], highlight:'ナガシマスパーランドとセットで1日。温泉は入れ墨対応あり。', rating:4.2, galleryBg:'linear-gradient(135deg,#d0c0c8,#a09098)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.0817, lng:136.7253 },

  // ═══════ 岐阜（近江境・大垣・関ヶ原・養老・岐阜市）═══════
  { id:'yorono_taki', emoji:'💦', name:'養老の滝', cat:'公園', catClass:'park', pref:'岐阜', loc:'養老町', addr:'岐阜県養老郡養老町高林1298-2', hours:'散策自由', closed:'なし', price:'無料', desc:'孝子伝説の滝。落差32mの名爆と渓谷公園。', keywords:['滝','渓谷','孝子伝説','公園','ハイキング'], play:['滝見物','渓谷ウォーク','養老公園','キャンプ'], highlight:'駐車場から徒歩30分程度。夏は涼しい。養老天命反転地も併設。', rating:4.2, galleryBg:'linear-gradient(135deg,#b0c8c0,#88a098)', ageGroups:[2,3,4,5,6,7,8,9,10], lat:35.2936, lng:136.5564 },
  { id:'yorotenmei', emoji:'🎨', name:'養老天命反転地', cat:'公園', catClass:'park', pref:'岐阜', loc:'養老町', addr:'岐阜県養老郡養老町高林1298-2', hours:'9:00〜17:00', closed:'月曜', price:'大人770円 / 小中310円', desc:'荒川修作のアート作品。歪んだ地形で平衡感覚を揺さぶる体験型アート。', keywords:['アート','建築','体験','荒川修作','不思議'], play:['アート散策','斜めの部屋','迷路','写真映え'], highlight:'子どもが走って楽しむ場所。ヘルメット貸出あり。歩きやすい靴で。', rating:4.3, galleryBg:'linear-gradient(135deg,#c8d8a0,#989880)', ageGroups:[3,4,5,6,7,8,9,10], lat:35.2875, lng:136.5656 },
  { id:'sekigahara', emoji:'⚔', name:'関ヶ原古戦場記念館', cat:'ミュージアム・体験', catClass:'museum', pref:'岐阜', loc:'関ヶ原町', addr:'岐阜県不破郡関ヶ原町関ヶ原894-55', hours:'9:30〜17:00', closed:'月曜', price:'大人500円 / 高校生300円 / 小中無料', desc:'関ヶ原の戦いの全貌を学べる体験型記念館。VRで戦場に立てる。', keywords:['関ヶ原','戦国','VR','体験','歴史'], play:['VR体験','グラウンドビジョン','展望台','古戦場'], highlight:'小学生以下無料。VRは人気なので整理券推奨。', rating:4.3, galleryBg:'linear-gradient(135deg,#a8a890,#80807088)', ageGroups:[4,5,6,7,8,9,10], lat:35.3777, lng:136.4650 },
  { id:'ogaki_castle', emoji:'🏯', name:'大垣城', cat:'ミュージアム・体験', catClass:'museum', pref:'岐阜', loc:'大垣市', addr:'岐阜県大垣市郭町2-52', hours:'9:00〜17:00', closed:'火曜', price:'大人200円 / 中学生以下無料', desc:'関ヶ原直前に石田三成が拠点とした城。歴史展示と天守。', keywords:['城','大垣','石田三成','歴史','関ヶ原'], play:['天守登閣','歴史展示','庭園','周辺散策'], highlight:'中学生以下無料。コンパクトで1時間程度で見学可能。', rating:3.9, galleryBg:'linear-gradient(135deg,#c8b898,#98*8878)', ageGroups:[3,4,5,6,7,8,9,10], lat:35.3628, lng:136.6172 },
  { id:'ogaki_park', emoji:'🌳', name:'大垣公園', cat:'公園', catClass:'park', pref:'岐阜', loc:'大垣市', addr:'岐阜県大垣市郭町2', hours:'常時開放', closed:'なし', price:'無料', desc:'大垣城を囲む市民公園。大型遊具と桜が自慢。', keywords:['公園','大型遊具','桜','子連れ','大垣'], play:['大型遊具','芝生広場','桜見物','水遊び場（夏）'], highlight:'春は桜が見事。駐車場は城見学とセットで使える。', rating:4.1, galleryBg:'linear-gradient(135deg,#c8d8b0,#909888)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.3625, lng:136.6194 },
  { id:'suitopia', emoji:'🎭', name:'スイトピアセンター 大垣', cat:'ミュージアム・体験', catClass:'museum', pref:'岐阜', loc:'大垣市', addr:'岐阜県大垣市室本町5-51', hours:'9:00〜17:00', closed:'火曜', price:'プラネタリウム大人500円 / 小中250円', desc:'プラネタリウム・科学館・音楽堂を備えた複合施設。', keywords:['プラネタリウム','科学館','音楽堂','室内','雨の日'], play:['プラネタリウム','科学体験','展示見学'], highlight:'プラネタリウムは時間指定。雨の日の避難所として重宝。', rating:4.0, galleryBg:'linear-gradient(135deg,#c0b0d0,#908098)', ageGroups:[3,4,5,6,7,8,9,10], lat:35.3611, lng:136.6247 },
  { id:'nango_taisha', emoji:'⛩', name:'南宮大社', cat:'ミュージアム・体験', catClass:'museum', pref:'岐阜', loc:'垂井町', addr:'岐阜県不破郡垂井町宮代1734-1', hours:'8:30〜17:00', closed:'なし', price:'無料', desc:'美濃国一の宮。朱色の社殿が美しい金属の神様。', keywords:['神社','一の宮','金属','朱色','垂井'], play:['参拝','境内散策','御朱印'], highlight:'美しい朱色の建築。駐車場広く子連れでゆったり参拝可能。', rating:4.2, galleryBg:'linear-gradient(135deg,#e8a898,#c08078)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.3386, lng:136.5500 },
  { id:'hirui_kofun', emoji:'🗿', name:'昼飯大塚古墳', cat:'ミュージアム・体験', catClass:'museum', pref:'岐阜', loc:'大垣市', addr:'岐阜県大垣市昼飯町', hours:'常時開放', closed:'なし', price:'無料', desc:'岐阜県最大の前方後円墳。公園整備で歩ける古墳。', keywords:['古墳','前方後円墳','歴史','公園','古代'], play:['古墳登り','歴史散策','芝生'], highlight:'古墳の上まで登れる珍しいスポット。子どもの学びに。', rating:3.8, galleryBg:'linear-gradient(135deg,#b0b088,#80806*8)', ageGroups:[4,5,6,7,8,9,10], lat:35.3833, lng:136.6333 },
  { id:'sekigahara_warland', emoji:'🪖', name:'関ヶ原ウォーランド', cat:'ミュージアム・体験', catClass:'museum', pref:'岐阜', loc:'関ヶ原町', addr:'岐阜県不破郡関ヶ原町関ヶ原1701-6', hours:'9:30〜16:30', closed:'不定休', price:'大人500円 / 小人300円', desc:'コンクリートの武者像240体！ユニークなB級歴史テーマパーク。', keywords:['武者像','B級','関ヶ原','昭和','野外展示'], play:['武者像めぐり','記念撮影','歴史学習'], highlight:'B級スポットとして子連れ親子に密かに人気。関ヶ原記念館と併せて。', rating:4.0, galleryBg:'linear-gradient(135deg,#b8a8a0,#88*7870)', ageGroups:[3,4,5,6,7,8,9,10], lat:35.3778, lng:136.4683 },
  { id:'gifu_castle', emoji:'🏯', name:'岐阜城（金華山）', cat:'ミュージアム・体験', catClass:'museum', pref:'岐阜', loc:'岐阜市', addr:'岐阜県岐阜市金華山天守閣18', hours:'9:30〜17:30（季節変動）', closed:'なし', price:'大人200円 / 小中100円（ロープウェー別途）', desc:'織田信長の居城。金華山山頂からの眺望は絶景。', keywords:['城','信長','金華山','ロープウェー','眺望'], play:['ロープウェー','天守','城下眺望','リス村'], highlight:'ロープウェー往復1,300円別途。山頂リス村も子どもに人気。', rating:4.3, galleryBg:'linear-gradient(135deg,#c0b098,#90807*0)', ageGroups:[3,4,5,6,7,8,9,10], lat:35.4344, lng:136.7822 },

  // ═══════ 京都北部（亀岡・木津川・南山城） ═══════
  { id:'hozugawa', emoji:'🚣', name:'保津川下り', cat:'ミュージアム・体験', catClass:'museum', pref:'京都', loc:'亀岡市', addr:'京都府亀岡市保津町下中島2', hours:'9:00〜15:30（最終便）', closed:'12-3月一部日程', price:'大人4,500円 / 4歳以上3,000円', desc:'亀岡から嵐山まで2時間の川下り。四季の渓谷美が絶景。', keywords:['川下り','保津川','亀岡','嵐山','船'], play:['川下り','渓谷景色','水しぶき','写真撮影'], highlight:'冬はこたつ船。雨天でも運航（要問合せ）。嵐山までの片道で帰りは電車。', rating:4.5, galleryBg:'linear-gradient(135deg,#a8c8c0,#7898a0)', ageGroups:[4,5,6,7,8,9,10], lat:35.0175, lng:135.5728 },
  { id:'torokko_kameoka', emoji:'🚂', name:'トロッコ亀岡駅（嵯峨野観光鉄道）', cat:'ミュージアム・体験', catClass:'museum', pref:'京都', loc:'亀岡市', addr:'京都府亀岡市篠町山本地黒', hours:'列車時刻表に準拠', closed:'水曜（繁忙期運行）', price:'大人880円 / 小人440円', desc:'嵐山までの渓谷沿いを走るトロッコ列車の亀岡駅。', keywords:['トロッコ','列車','嵐山','渓谷','観光'], play:['トロッコ乗車','渓谷景色','保津川下りとセット'], highlight:'春の桜、秋の紅葉は大人気。事前予約推奨。', rating:4.5, galleryBg:'linear-gradient(135deg,#c0a890,#908070)', ageGroups:[2,3,4,5,6,7,8,9,10], lat:35.0178, lng:135.5700 },
  { id:'keihanna', emoji:'🌳', name:'けいはんな記念公園', cat:'公園', catClass:'park', pref:'京都', loc:'精華町', addr:'京都府相楽郡精華町精華台6-1', hours:'9:00〜17:00', closed:'火曜', price:'無料（水景園400円）', desc:'広大な日本庭園と里山がある文化公園。子連れに優しい設計。', keywords:['日本庭園','里山','文化公園','芝生','ファミリー'], play:['芝生広場','観月橋','水景園','自然散策'], highlight:'広くてベビーカーOK。四季折々の景色が楽しめる。', rating:4.2, galleryBg:'linear-gradient(135deg,#c0d8b0,#909888)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:34.7492, lng:135.7797 },
  { id:'kizugawa_sports', emoji:'🌳', name:'山城総合運動公園（太陽が丘）', cat:'公園', catClass:'park', pref:'京都', loc:'宇治市', addr:'京都府宇治市広野町八軒屋谷1', hours:'9:00〜17:00', closed:'火曜', price:'入園無料（施設別途）', desc:'大型遊具・プール・アスレチックを備える京都府の大型公園。', keywords:['大型遊具','アスレチック','プール','太陽が丘','京都府'], play:['大型遊具','アスレチック','プール（夏）','芝生','BBQ'], highlight:'1日遊べる規模。夏の水遊び場が特に人気。', rating:4.3, galleryBg:'linear-gradient(135deg,#c8e0a8,#909888)', ageGroups:[1,2,3,4,5,6,7,8,9,10], lat:34.8733, lng:135.7992 },
  { id:'wazuka_tea', emoji:'🍵', name:'和束町茶畑ハイキング', cat:'ミュージアム・体験', catClass:'museum', pref:'京都', loc:'和束町', addr:'京都府相楽郡和束町', hours:'散策自由', closed:'なし', price:'無料（体験別途）', desc:'宇治茶の産地で急斜面の茶畑を眺めるハイキング。', keywords:['茶畑','ハイキング','宇治茶','景色','和束'], play:['茶畑ハイキング','茶摘み体験（時期）','写真撮影','カフェ'], highlight:'新茶の5月、紅葉の11月が特に美しい。駐車場は道の駅で。', rating:4.3, galleryBg:'linear-gradient(135deg,#b0c890,#88a070)', ageGroups:[3,4,5,6,7,8,9,10], lat:34.7728, lng:135.9344 },
  { id:'kasagi_camp', emoji:'⛺', name:'笠置キャンプ場', cat:'公園', catClass:'park', pref:'京都', loc:'笠置町', addr:'京都府相楽郡笠置町笠置河原地内', hours:'通年', closed:'なし', price:'区画料2,000円〜', desc:'木津川沿いの無料キャンプ場。デイキャンプ・川遊びに最適。', keywords:['キャンプ','川遊び','木津川','デイキャンプ','バーベキュー'], play:['キャンプ','川遊び','カヌー','バーベキュー','ハイキング'], highlight:'ペット連れOK。夏は水遊びに最適。事前予約推奨。', rating:4.2, galleryBg:'linear-gradient(135deg,#b0c0b0,#80907*8)', ageGroups:[3,4,5,6,7,8,9,10], lat:34.7670, lng:135.9481 },
  { id:'minamiyamashiro', emoji:'🍵', name:'道の駅 お茶の京都みなみやましろ', cat:'カフェ・レストラン', catClass:'cafe', pref:'京都', loc:'南山城村', addr:'京都府相楽郡南山城村北大河原', hours:'9:00〜17:00', closed:'なし', price:'入場無料', desc:'宇治茶の産地・南山城の道の駅。抹茶スイーツと地元野菜が充実。', keywords:['道の駅','抹茶','宇治茶','地元野菜','スイーツ'], play:['抹茶スイーツ','地元野菜買い','レストラン','お土産'], highlight:'抹茶ソフトが絶品。車旅の途中立ち寄りに最適。', rating:4.2, galleryBg:'linear-gradient(135deg,#b8c890,#889870)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:34.7589, lng:136.0022 },
  { id:'kameoka_cosmos', emoji:'🌸', name:'亀岡夢コスモス園', cat:'公園', catClass:'park', pref:'京都', loc:'亀岡市', addr:'京都府亀岡市吉川町穴太', hours:'9:00〜17:00（10月のみ）', closed:'開園期外', price:'大人800円 / 小人500円', desc:'800万本のコスモスが咲く秋限定の花園。', keywords:['コスモス','花畑','秋','期間限定','亀岡'], play:['コスモス鑑賞','写真撮影','花摘み'], highlight:'10月のみ開園。週末混雑、平日推奨。', rating:4.3, galleryBg:'linear-gradient(135deg,#f0b8c8,#c09098)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.0139, lng:135.5919 },
  { id:'hiyoshidam', emoji:'💧', name:'日吉ダム（スプリングスひよし）', cat:'公園', catClass:'park', pref:'京都', loc:'南丹市', addr:'京都府南丹市日吉町中神子ヶ谷68', hours:'10:00〜21:00', closed:'木曜', price:'温泉大人900円 / 公園無料', desc:'温泉・プール・ダム散策が一度に楽しめる総合施設。', keywords:['ダム','温泉','プール','BBQ','南丹'], play:['ダム見学','温泉','プール','BBQ','公園'], highlight:'子連れで1日遊べる規模。プールは夏季のみ。', rating:4.2, galleryBg:'linear-gradient(135deg,#a8c0d0,#7890a8)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.1833, lng:135.5044 },
  { id:'rurikeikogen', emoji:'🐑', name:'るり渓温泉（るり渓高原）', cat:'カフェ・レストラン', catClass:'cafe', pref:'京都', loc:'南丹市', addr:'京都府南丹市園部町大河内広谷1-14', hours:'10:00〜22:00', closed:'なし', price:'温泉大人1,700円 / 子ども1,000円', desc:'高原の温泉リゾート。イルミネーションと羊とのふれあいも。', keywords:['温泉','高原','イルミネーション','羊','リゾート'], play:['温泉','羊ふれあい','イルミネーション','BBQ'], highlight:'冬のイルミネーションが有名。日帰りでも宿泊でも楽しめる。', rating:4.3, galleryBg:'linear-gradient(135deg,#c0d0c8,#8898*8)', ageGroups:[0,1,2,3,4,5,6,7,8,9,10], lat:35.1444, lng:135.4250 }
];
  return SPOTS;
})();
